### ISSUE TITLE
Rendering nested JBuilder partials requires formats: [:json] to be passed

### ISSUE THREAD

**Issue by petedmarsh** [rails/jbuilder#134]
I render JSON using inside some HAML views in order to ship along an initial blob of JSON to the client. Since the change in https://github.com/rails/jbuilder/pull/120 I have found that rendering JSON/JBuilder partials is a little bit more cumbersome as `formats: [:json]` is no longer passed by default.

Where previously I had written:

`json.partial! 'xs/x', my_local: @some_value`

I now have had to change this to:

`json.partial! partial: 'xs/x', formats: [:json], locals: { my_local: @some_value }`

If I do not pass `formats: [:json]` I get a "Template not found" error. Ideally I'd like to go back to something like the original. Admittedly this only happens as I am rending a JBuilder template with nested partials into a HAML view, so perhaps it is too rare a use case to support directly.

My initial thought was a new method which is like `partial!` but can only render other JBuilder templates. After thinking about it for a little while, it's probably not a good solution.

**Comment by ryanb** [comment]
I'm running into this in Rails 6. Perhaps it has regressed? I find `formats: [:json]` necessary otherwise I get the missing template error.

**Comment by ryosk7** [comment]
I'm running in Rails 7.
I add `formats: [:json]` get template error.

It's solved just set like this.

```diff ruby
- render 'index', formats: :json, handlers: 'jbuilder'
+ render 'index'
```

I don't understand why I occurred this error.
