### ISSUE TITLE
How to return empty string instead of null as default?

### ISSUE THREAD

**Issue by regedarek** [rails/jbuilder#150]
Right now I get:

```
{"id":1,"name":"HerzASS ratiopharm","dosage":null}
```

I would like to return `""` instead of `null`

But as default. How to achieve that. I don't want to add `m.dosage || ""` for each attribute in my application.

I keeping this in my jbuilder views `views/api/documents/_document.json.jbuilder`

```
json.id document.id
json.category document.category
json.note document.note
json.attachments document.attachments do |attachment|
  json.url URI.join(request.url, attachment.url).to_s
end
json.created_at document.created_at
json.updated_at document.updated_at 
```

**Comment by bbozo** [comment]
Here's a simple proxy object for that: https://gist.github.com/bbozo/d1d75597ddf91996b098
