### ISSUE TITLE
Ability to use a layout with yield without parsing and encoding two times

### ISSUE THREAD

**Issue by alex88** [rails/jbuilder#172]
Actually to use a json template it's needed to `JSON.parse(yield)` which needs a re-parse of the encoded content and a re-encoding to the final json.

It would be nice to be able to skip this step to improve performances.

**Comment by jplethier** [comment]
I need to use a layout just like this, is there any news or plans to implement a way to not need to re-parse and re-encoding json again?

**Comment by Agent47DarkSoul** [comment]
@jplethier I tried creating the application.json.jbuilder and rails does use it as a layout and tries to render it. Unfortunately it raises an error regarding stored values in lib/action_view/flows.rb:13. I am trying to figure out what the issue is, will post an update when I do.

**Comment by amw** [comment]
I'm not sure why the opposition to include functionality like this. I think wrapping response data in a shared metadata structure is commonplace in API design. See `data`, `errors` or `meta` keys in JSON-API specification: http://jsonapi.org/format/.

Not a very pretty solution, but I managed to create my general response layout using json.erb and just pasting literal results of `yield` in a proper position. Much better than doing an extra round of `JSON.parse` & `JSON.generate`.

app/controllers/api/base_controller.rb:
```
class Api::BaseController < ActionController::Base
  layout "api.v1"
end
```

app/views/layouts/api.v1.json.erb:
```
{
<% if @api_errors.present? %>
  "errors": <%= JSON.dump @api_errors %>,
<% else %>
  "data": <%= yield %>,
<% end %>
  "meta": <%= JSON.dump @api_meta %>
}
```

**Comment by paulwalker** [comment]
It's pretty remarkable actually that Rails 5 (with all it's special emphasis on building JSON APIs) would launch without the ability to easily render the JSON-API standard, of which @wycats himself is a primary editor. All because dhh doesn't believe in metadata in api responses?

**Comment by Richard-Degenne** [comment]
Is there any news for this feature?

**Comment by seanpdoyle** [comment]
I've opened https://github.com/rails/jbuilder/pull/623 in an effort to implement this feature.
