### ISSUE TITLE
Is there a method to extract all attributes?

### ISSUE THREAD

**Issue by uiur** [rails/jbuilder#189]
I often write codes like this to extract all attributes from a record object or a hash. It's a pain.

``` ruby
json.array! @people do |person|
  json.extract! person, *person.attributes.keys
end
```

or

``` ruby
json.array! @hashes do |hash|
  json.extract! hash, *hash.keys
end
```

I want to write like this:

``` ruby
json.array! @people do |hash|
  json.extract_all! person
end  
```

Is there a better way to extract all attributes in Jbuilder?

**Comment by grillermo** [comment]
I used this solution, but for future googlers, make sure you merge before adding any attributes or you'll lose the previously defined keys
