### ISSUE TITLE
Helper methods not available in partials

### ISSUE THREAD

**Issue by samacs** [rails/jbuilder#227]
Hi,

I can't to access helper methods from a controller concern in a partial view:

This is where the helper methods are defined.

```
# app/controllers/concern/user_management.rb
module UserManagement
    extend ActiveSupport::Concern

    included do
        helper_method :current_user, :owner?, :system_user?
    end

    protected
    # ... methods
end
```

Application controller includes the `UserManagement` concern.

```
# app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include UserManagement
end
```

This is just an specific example, but in order to reuse my views, I want to be able to access concern helper methods in partials.

```
# app/controllers/admin/accounts_controller.rb
module Admin
    class AccountsController < ApplicationController
        # ...
        def show 
        end
        # ...
        private

        def set_account
            @account = Account.find(params[:id])
        end
    end
end
```

This is the view tree:

```
app/
    views/
        accounts/
            _account.json.jbuilder
            show.json.jbuilder
        branches/
            _branch.json.jbuilder
```

Helper methods are available in views:

```
# app/views/accounts/show.json.jbuilder
#
# I can access owner? and system_user? helper methods from concern here.
#
json.account do
    json.partial! 'accounts/account', account: @account
end
```

But can't access helper methods on partials:

```
# app/views/accounts/_account.json.jbuilder
json.extract! account, :id, :name
# Account has many branches
json.branches do
    json.array! account.branches, partial: 'branches/branch', as: :branch
end
```

This is the partial where I need to make a decision based on whether the user is a system user or an owner:

```
# app/views/branches/_branch.json.jbuilder
json.extract! branch, :name
if system_user?
    json.billing_addresses do
        json.array! branch.billing_addresses, partial: 'billing_addresses/billing_address', as: :billing_address
    end
elsif owner?
    json.billing_address do
        json.partial! 'billing_addresses/billing_address', billing_address: branch.billing_addresses.find_by_account(current_user.account_id)
    end
end
```

Is it possible to execute helper methods from partials? Isn't it in the same context as the view?

Thanks in advance.

**Comment by mmustala** [comment]
I has this issue also just a moment ago. In my case the issue was that my partial name was the same as the helper method name and the helper method got masked or something.

**Comment by mookie5dc** [comment]
I just ran into this same issue.  It seems like only methods in ApplicationHelper are available in the partials, but methods from other custom helpers are not included.  I did a workaround to move my methods into ApplicationHelper for now.

**Comment by rwz** [comment]
@mookie5dc what context you're invoking jbuilder in?

**Comment by rahulrajaram** [comment]
I just had this problem as well in a `.erb` file. I solved it by `extend`-ing the view helper from within the partial. So, it is definitely not a `jbuilder` problem.

**Comment by toby-1-kenobi** [comment]
I thought I had this problem, then I realised I had a space between `pluralize` and the opening parentheses of the arguments. Just thought I'd mention it here in case someone else has the same problem.

**Comment by mateusluizfb** [comment]
I adapted the @mookie5dc solution including the separated helper files in the application_helper. It is no longer necessary to add all the helper functions in the application_helper.
Example:
`
module ApplicationHelper
  include JsonFormaterHelper
end
`

**Comment by vcavallo** [comment]
In addition to @mateusluizfb's (and @mookie5dc's) solution, you can `extend Your::HelperClass` at the top of your jbuilder partial where you want to use the helper methods.

I'm not sure if it's a `good idea` - but it does work.
