### ISSUE TITLE
Template is missing on production environemt

### ISSUE THREAD

**Issue by williamhqs** [rails/jbuilder#233]
Just the same as this issue: https://github.com/rails/jbuilder/issues/221
I tried both gem 'jbuilder', '2.2.3' and gem 'jbuilder', '2.2.6'
Thanks!

**Comment by dhirajbajaj** [comment]
Hey, 
Is it fixed. 
I am on rails 4.1./ nginx / puma
Tried stackoverflow solution too: 
http://stackoverflow.com/questions/10520269/rails3-actionview-template-handlers-doesnt-work-on-production-server/13742784#13742784

Nothing worked. 

Will be great if someone can post a solution.
