### ISSUE TITLE
Render json with layout

### ISSUE THREAD

**Issue by karellm** [rails/jbuilder#235]
I try to do this:

``` ruby
# layout.json.jbuilder
json.merge! JSON.parse(yield)
json.status do
  json.code response.code
  json.message response.message
end
json.errors @errors || []


# in my controller
render json: {}, layout: true
```

This renders `{}` when I would want `{status: {...}, errors: []}`

Is it possible?

**Comment by TWGerard** [comment]
Did anyone ever figure out an answer to this?

`render json: {...}, layout: true` is still not rendering the jbuilder layout file.
