### ISSUE TITLE
JbuilderTemplate and JbuilderHandler should be namespaced.

### ISSUE THREAD

**Issue by pat** [rails/jbuilder#237]
Is there any reason - beyond existing dependent libraries - for `JbuilderTemplate` and `JbuilderHandler` not being namespaced under the `Jbuilder` constant? I think it's a fair expectation that gems keep their constants (beyond the one matching the gem's name) namespaced under that top-level constant - but perhaps there's a logical reason for this contrary approach here?

Certainly happy to submit a pull request if it's useful, though I realise it'd probably be something for v3 given it's clearly a breaking change for any dependent libraries.

**Comment by rwz** [comment]
> Is there any reason
There are none.

It was originally implemented like this by DHH, and there were not enough reasons to change it.

If I were rewriting Jbuilder today, I'd make it a single top-level module, like this:

```ruby
module Jbuilder
  class KeyFormatter; end
  class DependencyTracker; end
  class Proxy; end
  class Builder < Proxy; end
  class Template < Builder; end
  class Railtie; end
end
```

Maybe someday this will happen as version 3.
