### ISSUE TITLE
ActionView::Template::Error when building template

### ISSUE THREAD

**Issue by jerzygangi** [rails/jbuilder#239]
If I write this in my index.json.jbuilder:

```ruby
json.array!(@votes) do |vote|
  json.extract! vote, :id
end
```

The template works. It returns: [{"id":4},{"id":5},{"id":6}]

And if I write this in my index.json.builder:

```ruby
json.size @votes.size
```

The template works. It returns: {"size":3}

But if I put both of these together inside my index.json.builder:

```ruby
json.array!(@votes) do |vote|
  json.extract! vote, :id
end
 
json.size @votes.size
```

Rails / JBuilder throws an error:

```bash
Completed 500 Internal Server Error in 7ms
 
ActionView::Template::Error (no implicit conversion of String into Integer):
    2:   json.extract! vote, :id
    3: end
    4: 
    5: json.size @votes.size
  app/views/votes/index.json.jbuilder:5:in `_app_views_votes_index_json_jbuilder___1315342299324008536_70209538680880'
 
 
  Rendered /Users/jerzy/.rvm/gems/ruby-2.0.0-p353/gems/actionpack-4.1.7/lib/action_dispatch/middleware/templates/rescues/_trace.text.erb (0.7ms)
  Rendered /Users/jerzy/.rvm/gems/ruby-2.0.0-p353/gems/actionpack-4.1.7/lib/action_dispatch/middleware/templates/rescues/_request_and_response.text.erb (0.9ms)
  Rendered /Users/jerzy/.rvm/gems/ruby-2.0.0-p353/gems/actionpack-4.1.7/lib/action_dispatch/middleware/templates/rescues/template_error.text.erb (10.7ms)
```

Interestingly, this will throw the same error:

```ruby
json.array!(@votes) do |vote|
  json.extract! vote, :id
end
 
json.size 15
```

Is this a bug in JBuilder?

**Comment by rwz** [comment]
You template is broken. Here's what happens:

1) you call `json.array!` which essentially tells jbuilder that the resulting structure is an array
2) you fill the array with `@votes`
3) you're trying to add a key named `size` to an array, which doesn't make sense.

The response should either be an array or on object. Not both.

**Comment by jerzygangi** [comment]
Thanks for clarifying @rwz

**Comment by rwz** [comment]
You can have both by nesting the array in an object structure. Somewhat like this:

```ruby
json.votes @votes, :id
json.size @votes.size
```

Which will give you the following JSON:

```javascript
{
  "votes": [ { "id": 1 }, ... ],
  "size": 15
}
```
