### ISSUE TITLE
json.merge!

### ISSUE THREAD

**Issue by salmanasiddiqui** [rails/jbuilder#241]
This is more like a suggestion/improvement

    json.array!(@contacts) do |contact|
      json.merge! contact
    end

the above works perfectly but,
`json.merge! @contact`

doesnt.

I suppose that json.array! exposes records as something which json.merge! can handle.

if I change
`json.merge! @contact`
to
`json.merge! @contact.as_json`

it works fine, so cant the json.merge! be made a bit smarter to call as_json by itself on passed arguments?

**Comment by rwz** [comment]
Well, `merge!` expects a Hash argument and I'm not entirely sure why it event worked in the first place. Implicitly calling `as_json` is actually quite redundant and might negatively affect the performance. I'd recommend to manually pass `as_json`'ed values to it.
