### ISSUE TITLE
Rails 4.2 jbuilder default keys.

### ISSUE THREAD

**Issue by zw963** [rails/jbuilder#243]
When use with Rails 4.1, I setting ``attribute_names`` in model, 
it will reflect the default jbuilder keys, so I just need render ``#show`` like this
```rb
json.product @product     # => no extra keys arguments be specify anymore.
```
(although if no keys, must specify manully. e.g. ``json.(@product, *@product.attribute_names``

But, when update to 4.2, it not valid, seem like attribute_names not affect jbuilder.

I just want to know, any default value can be specify like 4.1 ? 

Thanks!

**Comment by rwz** [comment]
The initial assumption that `attribute_names` is relevant here is incorrect and harmful. It was only working as a coincidence by a combination of certain factors. Also, overriding methods that AR relies on is a bad practice and can backfire on all sorts of weird ways.

It's not a specified behavior and it's not how Jbuilder template should look like. It's using undefined behavior, namely, how the object responds to `to_json` method and if the JSON adapter actually cares for that.

In Jbuilder you're not supposed to pass non-JSON-friendly structures to the API. Once you do, nobody can say for sure what's gonna happen.

You can explicitly convert models to serializeable structures by manually calling `as_json` on them. So your code will look like this:

```ruby
json.product @product.as_json
```

**Comment by zw963** [comment]
Thanks a lot.

I found a new changed about as_json, I hope to ensure not misunderstood it.

e.g. 

in my controller, 
```rb
render :show
```

in my show.json.jbuilder:
```rb
json.product @product
```

my model: (additinal_fields is a serialization hash field, with attr1, attr2 key)
``rb
  def as_json(options={})
    super.merge!(additional_fields)
  end
```
in rails 4.1, Jbuilder render content include {'attr1' => 'attr1', 'attr2' => 'attr2'}, 
but rails 4.2 attr1 & attr2 is missing.

It seem like Rails 4.1, Jbuilder dependent as_json, But 4.2 not?

**Comment by rwz** [comment]
Again, if you're not explicitly calling `as_json` on the thing you're passing to Jbuilder, nobody can tell for sure what exactly is going to happen. It really depends on the MultiJSON adapter being used and a bunch of other app specific details. Also, overriding AR public API methods is a really bad idea and should be avoided.

**Comment by zw963** [comment]
Cool, very thanks for clarify!

**Comment by zw963** [comment]
But, still exist some wired things.

I want to use partial with jbuilder, some code like this

_product.json.jbuilder (product object is a really activerecord object with data)
```ruby
json.(product.as_json)     # always return []
```
But, 
```ruby
json.product(product.as_json)  # worked file
```
work fine.

should i add a new issue for this ?

**Comment by zw963** [comment]
just for clarify.
because I use differnce key name in products_controller#index and products_controller#show, 
so in partial, I use ```json.(product.as_json)```, just leave differnce key name in seperate view.
but, all my view use same data as value.

**Comment by zw963** [comment]
I add a new issue for this:
#246
