### ISSUE TITLE
Replace  nil value with empty string

### ISSUE THREAD

**Issue by shamithc** [rails/jbuilder#245]
Check  #244, Let's discuss this feature.

**Comment by tmarek** [comment]
Hi guys,

I don't know how I got onto this email list, but I am not contributing to this repo
please unsubscribe me - git@torsten-marek.de <mailto:git@torsten-marek.de>

thanks and greetings,

Torsten

**Comment by rwz** [comment]
Why is this feature necessary? Seems pretty arbitrary to me.

:-1: this.
