### ISSUE TITLE
Best approach for common API response

### ISSUE THREAD

**Issue by mikeys** [rails/jbuilder#250]
I'm building a Rails based API, and I'd like to use JBuilder for rendering the JSON responses.

The standard response for all calls for my API should be as follows:
```js
{
  status: "ok",
  error: "",
  data: {
    // Changes based on specified action, should be yielded
  }
}
```

Since I couldn't see any support for layouts in JBuilder, what's the best practice for supporting the above response?

Is there any way to do the above without adding 'status' and 'error' partials for every jbuilder view?

**Comment by rwz** [comment]
The best approach would probably be a view helper.

```ruby
def json_data_response
  json = local_assigns[:json]
  json.status "ok"
  json.error ""
  json.data &block
end
```

so you can use it in your Jbuilder views like this:
```ruby
json_data_response do
  json.foo "bar"
end 
```

to get
```javascript
{
  "status": "ok",
  "error": "",
  "data": { "foo": "bar" }
}
```

**Comment by mikeys** [comment]
That makes sense, thanks :)

**Comment by lneffa** [comment]
I'm having problems implementing this approach, I have placed the json_data_response helper inside application_helper.rb, and inside a jbuilder view I can access the helper, but local_assigns is undefined and any attempt to use defined? or access json module is undefined. 

What steps am I missing? Thank you for the help
