### ISSUE TITLE
Jbuilder response doesnt appear to be cachable. Cached response doesnt set content type to json

### ISSUE THREAD

**Issue by ktaragorn** [rails/jbuilder#252]
```
  get "/test" do
    Application.cache.fetch "test" do
      jbuilder :test
    end
  end
```
```
#test.jbuilder
json.text "test"
```
```
$ http get localhost:9292/test
HTTP/1.1 200 OK
Content-Length: 15
Content-Type: application/json
X-Build-Info: development.no_build_version
X-Content-Type-Options: nosniff

{
    "text": "test"
}
```
```
$ http get localhost:9292/test
HTTP/1.1 200 OK
Content-Length: 15
Content-Type: text/html;charset=utf-8
X-Build-Info: development.no_build_version
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block

{"text":"test"}
```

As you can see the `Content-Type` isnt set. However I verified that the response is `==` to the output of writing this response to cache and reading it back, So i assume the response is a "special" `String` and scrubbing it via cache is reducing it to a vanilla `String`.

**Comment by ktaragorn** [comment]
The cache is an `ActiveSupport::Cache::MemoryStore`

**Comment by ktaragorn** [comment]
The app itself uses Sinatra

**Comment by ktaragorn** [comment]
Found a "fix" which is to parse it and then serve it as `JSON` but doesnt seem to be pretty.
```
json(JSON.parse(Application.cache.fetch("test") do
      jbuilder :test
    end))
```

**Comment by ktaragorn** [comment]
The same happens with just using `json`. Nothing specific to jbuilder, closing

**Comment by ktaragorn** [comment]
For posterity, the right way is to just add `content_type "json"` in your response controller code

**Comment by rwz** [comment]
Yeah, right. Seems like cache is only caching response body, not other headers that `jbuilder` method sets.
