### ISSUE TITLE
Overriding ignore_nil! across the app

### ISSUE THREAD

**Issue by Ganasist** [rails/jbuilder#253]
I need to exclude null values in my JSON objects across the entire API. Is there an easier way to do this than including 'json.ignore_nil! true' in every view?

Also, when I include that in a view with multiple partials, only the first node responds. The other nodes all retain null values.

**Comment by rwz** [comment]
You could make an initializer to set global `ignore_nil` option globally:

```ruby
# config/initializers/jbuilder.rb
Jbuilder.ignore_nil true
```

About the multiple partials, I don't quite follow. Could you provide an example how an ignore nil option only work with the first object, but not the rest of them?

**Comment by Ganasist** [comment]
As you can see in the JSON object below, the first node (CONTRACTOR) has no NULL values when I add ignore_nil! to the top of the corresponding show.json.jbuilder file (even though I know there is a null value for 'phone'). So, ignore_nil! works for that, but the following BIDS node is full of NULL values, although it is drawn from the same file via a partial (see below). I've edited this JSON object to be less verbose than the actual one.

```json
    {
    "contractor": {
        "id": 2,
        "email": "xyz@openbid.contractors",
        "company_name": "OPENBID",
        "categories": ["Fencing", "Plumbing", "Design"],
        "review_count": 0,
        "review_average": "No reviews",
        "address": "Bakersfield, CA 93311, USA",
    "bids": [{
        "id": 973,
        "job_id": 78,
        "contractor_id": 2,
        "cost": 740,
        "accepted": false,
        "created_at": "2015-01-30T11:50:14.595Z",
        "updated_at": "2015-01-30T11:50:14.595Z",
        "rejected": false,
        "pdf_file_name": null,
        "pdf_content_type": null,
        "pdf_file_size": null,
        "pdf_updated_at": null
    }, {
        "id": 593,
        "job_id": 2031,
        "contractor_id": 2,
        "cost": 620,
        "accepted": false,
        "created_at": "2015-01-30T11:42:13.179Z",
        "updated_at": "2015-01-30T11:42:13.179Z",
        "rejected": false,
        "pdf_file_name": null,
        "pdf_content_type": null,
        "pdf_file_size": null,
        "pdf_updated_at": null
    }]}
```
Here is part of the show.json.jbuilder file:

```ruby
json.partial! 'api/v1/contractors/contractor', contractor: @contractor
json.partial! partial: 'api/v1/bids/bids', collection: @bids if @bids
```

**Comment by rwz** [comment]
I can't recreate that behavior:

```ruby
Jbuilder.ignore_nil true
Jbuilder.encode do |json|
  json.foo "bar"
  json.lol nil
end # => "{\"foo\":\"bar\"}"
```

If you still have this problem and sure it's not a configuration issue, please create a minimal showcase app recreating the bug and post the link here.
