### ISSUE TITLE
to_builder returns empty objects: [, , ]

### ISSUE THREAD

**Issue by itsSaad** [rails/jbuilder#254]
I have a `video.rb` model like this

    def to_builder
        Jbuilder.new do |vid|
          vid.id self.id
          vid.title self.title
          vid.video_file_name self.video_file_name
          vid.url self.absolute_url
          vid.view_count self.views
          vid.uploaded_at self.uploaded_at
          vid.video_size self.video_size
          vid.video_content_type self.video_content_type
        end
      end

in my view file i have this:

    json.blog_posts @blog_posts do |aPost|
        json.extract! aPost, :id, :title, :content, :author_name, :about_author, :published_at
        json.author aPost.author.to_builder if aPost.author
        json.cover_image_url aPost.cover_image_url
        json.images (aPost.images) do |image|
          json.uploaded_at image.uploaded_at
          json.url image.absolute_url
        end
        binding.pry
        json.videos aPost.videos.map {|a| a.to_builder}
    end

but i get `no implicit conversion of nil into Integer` error

because `json.videos aPost.videos.map {|a| a.to_builder}` is returning `[, , ]` which causes the error.

Whats wrong here?

**Comment by rwz** [comment]
`array.map{ |a| a.to_builder }` will not work in this case. You have to use `array.map{ |a| a.to_builder.attributes! }`

**Comment by itsSaad** [comment]
@rwz thanks! yes incase of videos it works. but incase i have a json.jbuilder file just with the following:
    @user.to_builder
or
    @user.to_builder.attributes!
or
    @user.to_builder.target!

it simply doesnt work. returns an empty hash.
Whats the difference here then?

**Comment by rwz** [comment]
What would you expect? You're not even calling jbuilders' API there.

**Comment by itsSaad** [comment]
ok. what im trying to do is use the to_builder method in the api response but i don't want to encapsulate it into any other object. How would i go about that besides using `extract!` or any such thing?

**Comment by johanstenberg92** [comment]
@itsSaad With the latest version I got this solved with

```
 def to_builder
    Jbuilder.new do |group|
      group.name name
      group.group_memberships group_memberships.map { |gm| gm.to_builder.attributes! }
    end
  end
```
