### ISSUE TITLE
Cannot understand how to use cache

### ISSUE THREAD

**Issue by robypez** [rails/jbuilder#255]
Hello, I have this index.json.builder but I cannot understand how can I add a fragment caching.

```
json.contents @contents do |content|
    json.id    content.id
    json.title content.name
    json.summary content.summary
    json.thumbnail content.square_crop_img_url
    json.url article_url(content)
end
```

Any hint?

**Comment by rwz** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
