### ISSUE TITLE
Proc creation error in encode

### ISSUE THREAD

**Issue by aportnov** [rails/jbuilder#264]
with jbuilder 2.2.13 running on jruby 1.7.19 I am getting the following error:

<pre>
E, [2015-05-09T11:52:16.573000 #24528] ERROR -- : tried to create Proc object without a block (ArgumentError)
org/jruby/RubyProc.java:130:in `new'
/Users/aportnov/.rvm/gems/jruby-1.7.19@mapping-service/gems/jbuilder-2.2.13/lib/jbuilder.rb:22:in `encode'
/Users/aportnov/.rvm/gems/jruby-1.7.19@mapping-service/gems/tilt-jbuilder-0.6.0/lib/tilt/jbuilder.rb:46:in `evaluate'
/Users/aportnov/.rvm/gems/jruby-1.7.19@mapping-service/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
/Users/aportnov/.rvm/gems/jruby-1.7.19@mapping-service/gems/sinatra-1.4.6/lib/sinatra/base.rb:822:in `render'
/Users/aportnov/.rvm/gems/jruby-1.7.19@mapping-service/gems/sinatra-1.4.6/lib/sinatra/base.rb:818:in `render'
/Users/aportnov/.rvm/gems/jruby-1.7.19@mapping-service/gems/tilt-jbuilder-0.6.0/lib/sinatra/jbuilder.rb:14:in `render_with_view_path_support'
/Users/aportnov/.rvm/gems/jruby-1.7.19@mapping-service/gems/tilt-jbuilder-0.6.0/lib/sinatra/jbuilder.rb:8:in `jbuilder'
</pre>
it is referencing line # 22:

<pre>
  # Yields a builder and automatically turns the result into a JSON string
  def self.encode(*args)
    new(*args, &::Proc.new).target!
  end
</pre>

**Comment by rwz** [comment]
What's the code you're trying to run?

**Comment by aportnov** [comment]
This is what my template looks like:
<pre>
json.array! entities do |entity|
    json.type        entity.entity_type
    json.description entity.description
    (entity.properties || {}).each{|k,v| json.__send__(k, v) }
    
    json.references (entity.references || []) do |ref|
        json.id     ref.source_id
        json.type   ref.ref_type
        json.origin ref.origin.alias
    end
end
</pre>

Thanks for your help,
Alex
