### ISSUE TITLE
jbuilder prevents custom scaffold_controller generator  to work

### ISSUE THREAD

**Issue by derencius** [rails/jbuilder#271]
I just created a new rails app to test a custom scaffold controller template, and it was not working. 

This commit seems to be causing it: 29c0014a9c954c990075d42c45c66075260e924b 

steps to reproduce this problem:

    rails new test_app
    cd test_app
    mkdir -p lib/templates/rails/scaffold_controller
    echo "hi" > lib/templates/rails/scaffold_controller/controller.rb
    rails g scaffold user email
    cat app/controllers/users_controller.rb # it should be hi

**Comment by rwz** [comment]
//cc @spastorino

**Comment by spastorino** [comment]
Thanks guys, test it and let me know.

**Comment by rwz** [comment]
@derencius can you confirm the issue is fixed?

**Comment by derencius** [comment]
@rwz yes, it works fine!  thanks!
