### ISSUE TITLE
Have `json.partial!` ignore nil by default

### ISSUE THREAD

**Issue by chrisnicola** [rails/jbuilder#274]
Or alternatively allow this behaviour to be configured. Right now it throws an error if it gets a nil model. This encourages an anti-pattern of nil checking which seems undesirable.

```
json.partial!(user.user_thing) unless user.user_thing.nil
```

**Comment by rwz** [comment]
Don't think that'd be such a great idea. I'd prefer not adding any more implicit behavior since partial is already doing too much for my taste.

**Comment by chrisnicola** [comment]
So throwing an exception on nil is the desired behaviour here? What about an explicit option for what to do on a nil value. It could also allow a nil template to be provided.

How is this handled for arrays BTW?

**Comment by rwz** [comment]
@chrisnicola yeah, I think throwing an exception is totally reasonable in this case. Arrays are not supported if I remember correctly.

**Comment by chrisnicola** [comment]
This seems to go against the general principle of avoiding nil checking. What about something like how Ruby handles this with `Hash#fetch` by providing a block or value to specify how to handle the nil case.

I'm really confused as to why an exception is preferable here?

**Comment by chrisnicola** [comment]
I realize I'm not entitled to a response on this, but I'd like to try to understand why throwing an exception is reasonable. Perhaps I am simply using it poorly, but I find I'm getting into a forced situation having having to nil check every single use of `partial!`. Is that intentional?

**Comment by brendon** [comment]
I stumbled upon this because the default scaffold for `json` responses in Rails renders a partial for `show` and expects the object to exist. Trying to `show` a non-existent record raises a 500 error instead of a 404 or even an empty `json` response. My fix was to do the following:

```
json.partial! "schools/school", school: @school if @school
```

This then returns an empty `json` object.
