### ISSUE TITLE
Setting an attribute with an empty hash does not render this attribute

### ISSUE THREAD

**Issue by born4new** [rails/jbuilder#275]
I tried to set an attribute to the empty hash using the *json.attribute_name* syntax, but it failed. Is this behaviour by design?

```ruby
json.test do
  json.extra_info {}
  json.set! :extra_info2, {}
end
```

This yields the following json:

```ruby
{:test=>{:extra_info2=>{}}
```

Furthermore, if I do the following: 

```ruby
json.test do
  json.extra_info []
  json.set! :extra_info2, {}
end
```

this works as expected, i.e.

```ruby
{:test=>{:extra_info=>[], :extra_info2=>{}}}
```

**Comment by rwz** [comment]
> Is this behaviour by design?

I believe this is a bug.

**Comment by born4new** [comment]
Hi there,

I dug a bit deeper and it's not actually a bug in jbuilder. It is due to the way the empty hash is interpreted by ruby (in this case, to a block). If I force the hash to be a parameter, and not a block start, it works:

```ruby
json.test do
  json.extra_info({})
end
```

yields the expected result. Closing this.

**Comment by liorbrauer** [comment]
I'm struggling with this as well:

```ruby
json.replies do
  post.replies.last(10).each do |reply|
    json.set! reply.id do
    ...
    end
  end
end
```
 I would like to iterate over the replies association, and if there are no matches, I want the json to return

```json
{
  post: {
    ...
    replies: {}
  }
}
```

but instead, the `replies` attribute is not rendered. How can I achieve this?

**Comment by buiminhtri318** [comment]
hi @liorbrauer, did you find the solution for this yet? I am having same problem. Thanks.

**Comment by liorbrauer** [comment]
hey @buiminhtri318, I did find a solution. What I'm doing (using the same example as above):

```ruby
json.replies({})
json.replies do
  post.replies.last(10).each do |reply|
    json.set! reply.id do
    ...
    end
  end
end
```

which feels a bit hacky to me, but it works. hope this helps!

**Comment by rwz** [comment]
Oh, I got it. This is due to ambiguity in ruby syntax.

`json.thing {}` is read by ruby as this passing an empty block to a method, which results in nothing. If you want to make sure Ruby parses it as a hash, you can add explicit parens or just pass hash as a variable:

```ruby
json.thing({})
# or
thing = {}
json.thing thing
```

**Comment by rwz** [comment]
@liorbrauer 

solution to your problem:

```ruby
# replies_helper.rb
def last_post_replies_as_json(post)
  post.replies.last(10).inject({}) do |m, reply|
    m.merge! reply.id => reply.body
  end
end

# post.json.jbuilder
json.replies last_post_replies_as_json(posts)
```

**Comment by skalee** [comment]
I'm doing following:

```
json.empty object do
  json.merge! Hash.new
end
```

I suggest adding a dedicated and descriptive method for that, maybe `Jbuilder#empty!` or `Jbuilder#object!`, because such approach is useful in some cases. For example:

```
for item in collection
  json.set! item.key do
    unless item.should_render?
      json.merge! Hash.new # will make empty object instead of null
      next
    end
  end

  json.title item.title # etc.
end
```
