### ISSUE TITLE
Rails Request Rspec Jbuilder, request.body is a StringIO object

### ISSUE THREAD

**Issue by johanstenberg92** [rails/jbuilder#276]
I'm working on a project in Ruby on Rails, and I decided to use Jbuilder for handling the json serialization of my models. However when using Rspec to test my controllers with request specs, using the `*.json.jbuilder` views, my `request.body` comes back as a `StringIO` object, not a `String`.

My method in the affected controller looks like:

    def list
      @groups = ...
    end

And the `list.json.jbuilder` file looks like:

    json.array! @groups, :id, :name

The test snippet looks like:

    get '/api/v1/groups', { :format => :json }
    puts request.body.class.name # gives StringIO instead of String...

I'm using Rails 4.2.2, Ruby 2.2.2, Rspec-Rails 3.3.2 and JBuilder 2.3.0

I have set in my `rails_helper.rb`:

    config.render_views # tried with config.render_views = true too

The stacktrace for the exception is:

    Failure/Error: expect(json['groups'].length).to eq (2)
     TypeError:
       no implicit conversion of StringIO into String

I can add that it *works* when not using Rspec.

Thanks

**Comment by johanstenberg92** [comment]
Oh my god, the problem was me using `request.body` instead of `response.body`. Sorry.

**Comment by PeaceS** [comment]
@johanstenberg92 I just ran into the same problem, with the same human error!
just drop by to say that this issue of your just help me after struggling for almost an hour

Thank you!
