### ISSUE TITLE
jbuilder local variables do not work with jruby since 2.3.0

### ISSUE THREAD

**Issue by badazz91** [rails/jbuilder#277]
Hi guys,

when I pass a local variable to a partial inside of a json.array block, it is not accessible in the partial.
The strange thing is, that this only occurs when using jruby and jbuilder 2.3.0. If I switch back to 2.2.16 it also works with jruby.
With mri-ruby it also works with 2.3.0.

**Comment by rwz** [comment]
Can you provide a code example?

**Comment by sytzeloor** [comment]
I encountered the same issue. Here is a code sample:

```
json.ranking(
  @course.students,
  partial: 'api/v1/students/rank',
  as: :student,
  student_id: @student.id
)
```

The variable `student_id` is not available in the `rank` partial.

**Comment by rwz** [comment]
Well, it's not supposed to work this way. Try this:

```ruby
json.ranking @course.students,
  partial: "api/v1/students/rank",
  as: :student,
  locals: { student_id: @student.id }
```

**Comment by fpauser** [comment]
@sytzeloor Why ruby-version are you using?
