### ISSUE TITLE
`cache!` has different results when caching is on/off

### ISSUE THREAD

**Issue by sgonyea** [rails/jbuilder#278]
*Edit:* Appears I was wrong. This seems to be a 2.0.8-specific bug. Looks like 2.3.0 fixed this issue... though I don't see a test covering this specific case.  Is there a possibility of a 2.0.x bugfix?

Given the below code, If I have, say, 45 records then I'll get 45 records with caching enabled.  If caching is not enabled, I'll only get 15 records (the last 15).

```ruby
@comments.each_slice(30) do |comment_slice|
  json.cache! comment_slice do

    json.array! comment_slice do |comment|
      json.partial! comment
    end

  end # cache comment_slice
end # each_slice
```

*Update: the below is only true for 2.0.8.*

It would seem that this is a result of the `cache!` method only calling `merge!` if caching is turned on:

```ruby
  def cache!(key=nil, options={})
    if @context.controller.perform_caching
      value = ::Rails.cache.fetch(_cache_key(key, options), options) do
        _scope { yield self }
      end

      merge! value
    else
      yield
    end
  end
```

**Comment by rwz** [comment]
Is there anything preventing you from updating to 2.3?

**Comment by sgonyea** [comment]
@rwz:  Sorry, I was in a debug-flurry and somehow convinced myself that jbuilder 2.3 required rails 4.  My bad!  I'll close this issue.
