### ISSUE TITLE
array! with attributes and block at the same time

### ISSUE THREAD

**Issue by clamoris** [rails/jbuilder#283]
It would be nice to have 
```ruby
  json.array! @all_tests, :_id, :name  do |test|
    json.is_current_user_owner test.owner == current_user
  end
```
instead of, 

```ruby
  json.array! @all_tests  do |test|
    json._id test._id
    json.name test.name

    json.is_current_user_owner test.owner == current_user
  end
```

especially for large objects with many attributes

**Comment by mayatskiy** [comment]
+1

**Comment by novikserg** [comment]
I can implement that, what do you think @rwz?

**Comment by vincentwoo** [comment]
I dunno if I'm keen on additional magic here. Is the new form of `array!` worth the confusion? The typical approach here seems more rubyish (less surprising):

```ruby
 json.array! @all_tests do |test|
    json.extract! test, :_id, :name
    json.is_current_user_owner test.owner == current_user
  end
```

**Comment by novikserg** [comment]
Oh yeah, I didn't know about `array!`, then it definitely is not.

**Comment by yordis** [comment]
@vincentwoo I am agree with you, that's add an extra layer in `array` implementation without any valuable reason

**Comment by rwz** [comment]
The performance is not the issue here. The issue is increasingly broad way api can react to every possible method invocation tends to add more magic and complexity that produces slower and harder-to-maintain and support code for a use case of a questionable value.
