### ISSUE TITLE
Outputting a String

### ISSUE THREAD

**Issue by jcdavison** [rails/jbuilder#284]
Hi All,

I'm not sure if this is a bug, probably not but since a co-worker reviewed the docs with me and arrived at the same conclusion, I figured I'd post my question just the same.

Given the docs for bolting a `to_builder` like method onto an existing active record class, 

```ruby
class Person
  # ... Class Definition ... #
  def to_builder
    Jbuilder.new do |person|
      person.(self, :name, :age)
    end
  end
end

class Company
  # ... Class Definition ... #
  def to_builder
    Jbuilder.new do |company|
      company.name name
      company.president president.to_builder
    end
  end
end

company = Company.new('Doodle Corp', Person.new('John Stobs', 58))
company.to_builder.target!

# => {"name":"Doodle Corp","president":{"name":"John Stobs","age":58}}
```

In particular, the return value as referenced,

```
# => {"name":"Doodle Corp","president":{"name":"John Stobs","age":58}}
```

I would expect to be not a string, rather an hash or struct, json or something.

I'm currently getting a string back given,

```ruby
# ...
  def to_builder
    Jbuilder.new do |bottle|
      bottle.(self, *DISPLAY_ATTRIBUTES)
    end
  end

# ...
```
where `DISPLAY_ATTRIBUTES` is an array of attrs being dynamically generated, etc, I'm getting a return value of 

```
irb(main):059:0> Bottle.last.to_builder.target!
  Bottle Load (0.6ms)  SELECT  "bottles".* FROM "bottles"  ORDER BY "bottles"."id" DESC LIMIT 1
=> "{\"appellation\":\"DOC20\",\"condition\":null,\"country\":\"Italy\",\"cuvee\":null,\"foodPairing\":null,\"grapeVariety\":null,\"id\":3383,\"notes\":null,\"price\":200000,\"producer\":\"Producer #20\",\"productId\":835,\"region\":\"Region #20\",\"secondaryAppellation\":null,\"size\":null,\"subRegion\":\"waffles\",\"sweetness\":null,\"tastingNotes\":null,\"vintage\":2002,\"wineType\":\"Champagne\"}"
irb(main):060:0> Bottle.last.to_builder.target!.class
  Bottle Load (0.7ms)  SELECT  "bottles".* FROM "bottles"  ORDER BY "bottles"."id" DESC LIMIT 1
=> String
```

I would generally expect based on the docs not to be getting a String return value.  Is this an error in my usage of the Gem, if so, what is a possible fix ?  I've currently moved away from using jbuilder and am manually deconstructing the object into a hash and passing that to react.

Cheers,

JD

**Comment by jcdavison** [comment]
So maybe I'm missing the point of what `.target!` is for and potentially I could be using `.attributes!` but that begs a bigger question about why I'm concerned with structure so much ?

**Comment by jeremywadsack** [comment]
I expect that `target!` returns JSON, not a ruby Hash. So the string is correct. The documentation does make it seem like it would be a ruby construct (because of the "=>"), but it also happens to be JSON.

If you want a Ruby hash of name-value pairs I think you can do something much simpler: 

```ruby
def to_hash
  attributes.slice(*DISPLAY_ATTRIBUTES)
end
```

**Comment by rwz** [comment]
> he documentation does make it seem like it would be a ruby construct (because of the "=>"), but it also happens to be JSON.

Could you point out where did you see documentation mention `=>` on `target!`?

**Comment by jcdavison** [comment]
@rwz are you addressing me or @jeremywadsack but I must have seen what I referenced in the readme.  i've generally moved on from this being an issue for me (i must have found a work around) cause I'm not still thinking about the problem. Thanks for following up

**Comment by jeremywadsack** [comment]
@rwz Not sure. What I see now in the README is this:

```
company.to_builder.target!

# => {"name":"Doodle Corp","president":{"name":"John Stobs","age":58}}
```

The confusing thing is that looks like a hash. Not because of `=>` but because it's not a quoted string. If the response from `#target!` is a string I would expect that last line to look like this:

```
# => "{\"name\":\"Doodle Corp\",\"president\":{\"name\":\"John Stobs\",\"age\":58}}"
```
