### ISSUE TITLE
Odd Jbuilder Response

### ISSUE THREAD

**Issue by chirag7jain** [rails/jbuilder#291]
```
class LineItem
  def stock_status
    8, true
  end
end
```

Template

```
json.stock, json.required_stock = line_item.stock_status
```

Response

```
stock=: 6,
required_stock=: true
```

Want the response to be

```
stock: 6,
required_stock: true
```

why is this happening

http://stackoverflow.com/questions/32218673/odd-jbuilder-response-rubyonrails-jbuilder-gem-json-response

**Comment by vincentwoo** [comment]
jbuilder doesn't support that syntax - values are assigned with method calls, not the `=` assignment operator. jbuilder is assuming that you are attempting to assign values to two keys, one named `stock=` and another named `required_stock`

this is if you had done

```ruby
json.stock= 6
json.required_stock= true
```
