### ISSUE TITLE
jbuilder files extraction

### ISSUE THREAD

**Issue by alienxp03** [rails/jbuilder#297]
I'm using <a href='https://github.com/rails-api/rails-api' target='_blank'>rais-api</a> to create an API server, and using jbuilder to present the json. On top of that, I'm documenting the APIs using <a href='https://github.com/richhollis/swagger-docs' target='_blank'>swagger_docs</a>. I'm thinking about to extracting all `jbuilder` files that I've created and create appropriate <a href='https://github.com/richhollis/swagger-docs#documenting-a-controller' target='_blank'>swagger_model</a> so that I can document the response properly on `swagger-docs` (might be using a script, or just plain Ruby).

Would this be a good idea, or is there any other good approach for this?

**Comment by jeremy** [comment]
Not sure exactly what you're suggesting, @alienxp03, but it sounds like you've got a good concept to pursue. Give it a shot, make something real, and share it with others 😁

**Comment by ritammehta** [comment]
@alienxp03 is this something you ever figured out? Running into this issue now.
