### ISSUE TITLE
Issues with prepend_view_path and append_view_path

### ISSUE THREAD

**Issue by uberllama** [rails/jbuilder#300]
Hi friends. I'm wracking my brain this am trying to figure out why the hell I can't get these working with jbuilder.

I have two versioned APIs:

* api/v1
* api/admin/v1

My admin API controllers are more permissive than the standard API controllers, but most of them should be able to reuse the same .jbuilder templates as the customer API. I have tried several combinations of `prepend_view_path` and `append_view_path` in my admin api base controller pointing to the non admin view directory "app/views/api", with no luck.

```ruby

class Api::Admin::ApplicationController < ActionController::Base
  before_action :set_path

  def set_path
    # prepend_view_path "app/views/api"
    # prepend_view_path "app/views/api/v1"
  end
```

Do I need more coffee or is there something intrinsic to Jbuilder that wold prevent this from working? Enlightenment appreciated.

**Comment by jeremy** [comment]
`prepend_view_path` and `append_view_path` are class methods 😊

You can manipulate `view_paths.push/unshift`
