### ISSUE TITLE
Is there a way to prepend model's name in jbuilder

### ISSUE THREAD

**Issue by abhiQmar** [rails/jbuilder#302]
When there are similar keys in two models, is there a way to prepend model's name with an underscore using a function.
```ruby
json.(car, :id, :name)
json.(location, :id, :name)
```
I would like an output like (without having to manually enter all the keys)
```json
{
"car_id": "12",
"car_name": "AUDI",
"location_id": "1",
"location_name": "Cali"
}
```

**Comment by malomalo** [comment]
I believe you can use a key formatter:

```ruby
json.key_format! ->(key){ "car_#{key}" }
json.(car, :id, :name)
```

**Comment by abhiQmar** [comment]
Thanks @malomalo :)
