### ISSUE TITLE
Rails not loading my show.json.jbuilder file

### ISSUE THREAD

**Issue by iDev0urer** [rails/jbuilder#306]
I have been trying to get Rails to load my `show.json.jbuilder` file by itself, but the only way I am able to get it working for now is by including a `render '/users/show.json.jbuilder'` line in my User controller. The error I'm getting is:

``` 
Missing template users/show, application/show with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :jbuilder]}. Searched in:
```

As you can see it is looking for jbuilder, but for some reason it isn't finding it. As soon as I change my show method to:

```
def show
    @user = User.find(params[:id])
    render 'users/show.json.jbuilder'
  end
```

it works. Any ideas?

**Comment by awkerney** [comment]
From what I can tell (with limited Rails experience) by default Rails looks for an .html.erb file and isn't finding one. I think the following should help  http://api.rubyonrails.org/classes/ActionController/MimeResponds.html#method-i-respond_to

```ruby
def show
  @user = User.find(params[:id])
   respond_to do |format|
      format.json
   end
end
```

**Comment by rwz** [comment]
From the error message it's clear that Rails is looking for an HTML template and not finding it, since Jbuilder's template type is JSON. This is not a Jbuilder question, please consider using StackOverflow to ask general Rails questions.

**Comment by iDev0urer** [comment]
I figured it out. I wasn't including .json in the URL so it was looking for the wrong files.

**Comment by aayush-practo** [comment]
@iDev0urer i am facing the same problem, however if I rename `show.json.jbuilder`to `show.jbuilder` it is working fine. but i did not get what exactly you meant by including .json in URL. which URL you are talking about.. do you mean `render show.json`? I tried it, but it also did not work

**Comment by kangkyu** [comment]
In my case the URL @watzon mentioned can be (if `httparty` is used)

```rb
HTTParty.get("http://example.com/users/1").parsed_response       # does not work. error.
HTTParty.get("http://example.com/users/1.json").parsed_response  # works
```

When I changed the filename `show.json.jbuilder` to `show.jbuilder` it also worked. (does not need `.json` of `1.json`) Thank you @aayush-practo  

By the way, I'm curious why `HTTParty.get("http://example.com/users/1")` and `show.json.jbuilder` don't work together. It could be documented somewhere, but I'm not sure

**Comment by buhrmi** [comment]
Having this problem too... Why is Rails trying to serve HTML even tho I'm sending an `Accept` header with the value `application/json`. This is weird.

**Comment by Korak-997** [comment]
Had same problem but this worked out for me :

``
render 'filename.json.jbuilder'
``

**Comment by brendon** [comment]
@buhrmi, did you ever figure it out? I'm having this problem on Rails `6.0.x`.

**Comment by juanca** [comment]
Same issue. 

- Ruby 3.0.2
- Rails 6.1.4
- Jbuilder 2.7

```ruby
  def show
    render json: @view # does not work, uses normal json
  end
```

```ruby
  def show
    render 'views/show.json.jbuilder' # does work
  end
```

**Comment by Terencedifferent** [comment]
> Having this problem too... Why is Rails trying to serve HTML even tho I'm sending an `Accept` header with the value `application/json`. This is weird.





https://stackdev.space/questions/what-is-the-best-way-to-display-json-within-a-partial
