### ISSUE TITLE
Compatibility with Rails 5.0

### ISSUE THREAD

**Issue by mvastola** [rails/jbuilder#307]
With the release of Rails 5.0.0.beta1 just days ago, many users (myself included) are seeking to upgrade their current Rails 4.2 apps to ensure forward-compatibility with this new version of Rails and to make use of its new features and capabilities.

Currently, the `jbuilder.gemspec` includes the line:
```
s.add_dependency 'activesupport', '>= 3.0.0', '< 5'
```
which prevents usage of this gem (or even experimentation with it) in this new version of Rails.

I would like to request that jbuilder be made compatible with Rails 5.0.

**Comment by rwz** [comment]
Mind sending a PR?

**Comment by mvastola** [comment]
I'm more than happy to change the gemspec and run the test suite and see if everything passes. 
Unfortunately, I'm not very familiar with the internals of this gem (nor Rails 5), so I might not be the best person to troubleshoot any compatibility issues with the new Rails.

Stand by for updates.

**Comment by matthewd** [comment]
FYI, I don't recall any deprecation-less changes in AS, so it's probably fine.

**Comment by mvastola** [comment]
So clearly I didn't get to this last night. I'll try again for tonight I'm UTC-5, but people should feel free to beat me to it if they so desire!
On Dec 21, 2015 12:34 AM, Matthew Draper <notifications@github.com> wrote:FYI, I don't recall any deprecation-less changes in AS, so it's probably fine.

**Comment by mvastola** [comment]
Update: So I'm afraid I'm running into difficulties getting the appraisals gem to work correctly. It might be best if someone with a deeper knowledge of jbuilder gives this a go. (I had assumed I could just change the dependency, run `bundle update` and `bundle exec rake test`, but that seems to not be the case -- or at least when I attempt this I get no output.)

NB: I did manage to -- after toying with removing appraisal entirely and then editing Gemfile (on my local copy) to include Rails 5.0 / Arel 7.0 / Rack 2.0 (which no longer need to fetch from github) -- run the included tests and see them all pass.. So all signs point to jbuilder not needing any actual changes. I just don't feel comfortable -- from my present understanding of appraisal -- generating a PR that's inclusive of all the changes needed.

**Comment by mvastola** [comment]
FYI, I figured this out, so PR #309 has been made.

**Comment by mvastola** [comment]
PR #309 has been merged. Closing.
