### ISSUE TITLE
Setting attribute by iterating on an empty list doesn't render the attribute

### ISSUE THREAD

**Issue by marienfressinaud** [rails/jbuilder#313]
As stated by https://github.com/rails/jbuilder/issues/275#issuecomment-151504460, the following code doesn't render the attribute if `post.replies` is empty:

``` ruby
json.replies do
  post.replies.each do |reply|
    json.set! reply.id do
      ...
    end
  end
end
```

If it is not a bug, how can I force empty hash to be generated?

**Comment by mbajur** [comment]
+1

**Comment by nflorentin** [comment]
You certainly already found out a solution but might be useful for others.

It's a bit dirty but you can achieve this goal doing:

```ruby
json.replies do
  post.replies.each do |reply|
    json.set! reply.id do
      ...
    end
  end
end
json.replies({}) if post.replies.empty? # parenthesis are very important !
```

#275

**Comment by marienfressinaud** [comment]
Actually I took another approach by defining a helper method:

```ruby
module JbuilderHelper
  def json_each(json, objects, json_key_name)
    # Fix bug from JBuilder when `objects` is empty the attribute is not generated
    # See https://github.com/rails/jbuilder/issues/313
    return json.set! json_key_name, {} if objects.empty?

    json.set! json_key_name do
      objects.each do |object|
        yield object
      end
    end
  end
end
```

that you can use as following in your JBuilder view:

```ruby
json_each json, replies, :replies do |reply|
  ...
end
```

I'm not totally satisfied by this solution (especially because you have to pass `json` as parameter) but it's better to avoid redundancy.

**Comment by robin850** [comment]
No, this is not a bug, this is how Ruby works ; `each` is a no-op on an empty collection. I guess we can give this a close. Thanks for reporting anyway !

**Comment by marienfressinaud** [comment]
Indeed, it is how Ruby works, but we aren't just executing some code, we are generating Json. In my first example, one could expect the key to be generated… At least it is a feature that I would expect from JBuilder, to be able to generate easily an empty array. The solutions that we suggested with @nflorentin are not very handy or even well designed… do you have a better approach to suggest or would you be interested in a PR to implement such a behavior?

**Comment by robin850** [comment]
> we aren't just executing some code, we are generating Json

You actually are ; Jbuilder is just a handy Ruby DSL. The goal is not to provide a new flavor to output JSON but to let the user use Ruby with some nice wrapping to make it easier to output things.

I'm certainly not able to think outside the box here but I guess it would be pretty useless to implement a method for such thing. Also, in regular ERb views, I often find myself doing things like:

~~~erb
<% if @articles.any? %>
  ...
<% else %>
  No articles available for the moment.
<% end %>
~~~

Jbuilder templates work like regular templates. Also, maybe I'm totally wrong but given how easy it is to turn around this problem, I guess it will be difficult to come up with an API smoother or easier than an `if / else`. 🤷‍♂️
