### ISSUE TITLE
Faster JSON backends

### ISSUE THREAD

**Issue by TravisTam** [rails/jbuilder#315]
Is there any sample for using multi_json? Seems it is hard to know how to find how to config below setting.
```
require 'multi_json'
MultiJson.use :yal
```

**Comment by nflorentin** [comment]
You just have to add `gem 'oj'` or any gem adapter supported by MultiJson in your gemfile. Jbuilder already uses MultiJson and MultiJson will use the fastest adapter available with a fallback on default json adapter.

in rails console, before:
```ruby
> MultiJson.current_adapter
MultiJson::Adapters::JsonGem < MultiJson::Adapters::JsonCommon
```

after:
```ruby
> MultiJson.current_adapter
MultiJson::Adapters::Oj < MultiJson::Adapter
```

**Comment by jeremy** [comment]
> The use method, which sets the MultiJson adapter, takes either a symbol or a class (to allow for custom JSON parsers) that responds to both .load and .dump at the class level.

https://github.com/intridea/multi_json 🖖
