### ISSUE TITLE
Jbuilder with Rails 5.0.0 beta2

### ISSUE THREAD

**Issue by abhi-patel** [rails/jbuilder#317]
Having the following issue with rails 5.0.0 beta2
```Ruby
class ApplicationController < ActionController::API
```

PostsController
```Ruby
class PostsController < ApplicationController

  def first
    render json: {error: 'This is Error'}
  end

  def second
    @data = [1,2,3]
    render json: {error: 'This is Error'}
  end
end
```

app/views/posts/second.json.jbuilder
`json.key @data`

(Have not created template for 'first' action)

http://localhost:3000/first.json
```JSON
{
"status": 500,
"error": "Internal Server Error",
"exception": "#<ActionView::MissingTemplate: Missing template posts/first, application/first with {:locale=>[:en], :formats=>[:json], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :jbuilder]}. Searched in: * "/Users/a/workspace/new_api/app/views" >"
}
```

http://localhost:3000/second.json
```JSON
{
"key": [1,2,3]
}
```
The issue is it never considers the options(specifically :json) passed to render call in controller action and always tries to render the view template for the action.

I think the issue is with method 'render_to_body' of ActionView::Rendering and ActionController::Renderers

Since ActionController::API does not include ActionView::Layouts and jbuilder includes it specifically, somehow it executes render_to_body from ActionView::Rendering before ActionController::Renderers and hence always renders template irrespective of ':json' option specified in render call from controller.

Thoughts?

**Comment by v3rron** [comment]
+1

**Comment by neroniaky** [comment]
+1

**Comment by rwz** [comment]
This seems like a Rails issue to me. Why jbuilder?

**Comment by abhi-patel** [comment]
Was planning to post to Rails issues only.

Just curious that with application controller inherited from ``ActionController::API`` everything works fine(of course without view rendering part), But after adding jbuilder to gemfile, Normal ``render :json`` calls starts breaking and it expects template for each action.

Thought it could be because of inclusion done by jbuilder in railtie.rb (Correct me If I am wrong)

**Comment by schmijos** [comment]
I've the same issue. After including *jbuilder* the following error message appears for one of my tests:

```
ActionView::MissingTemplate: Missing template sensors/create, application/create with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :jbuilder]}. Searched in:
* ".../app/views"
...
```

---

The only changes I made in the project have the following diff:

```diff
diff --git a/Gemfile b/Gemfile
index 3f6c84f..4aecc62 100644
--- a/Gemfile
+++ b/Gemfile
@@ -7,6 +7,7 @@ gem 'pg'
 gem 'puma'

 gem 'redis', '~> 3.0'
+gem 'jbuilder'

 # Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
 # gem 'rack-cors'
diff --git a/Gemfile.lock b/Gemfile.lock
index 479f091..583f5fa 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -53,6 +53,9 @@ GEM
     globalid (0.3.6)
       activesupport (>= 4.1.0)
     i18n (0.7.0)
+    jbuilder (2.4.1)
+      activesupport (>= 3.0.0, < 5.1)
+      multi_json (~> 1.2)
     json (1.8.3)
     loofah (2.0.3)
       nokogiri (>= 1.5.9)
@@ -62,6 +65,7 @@ GEM
     mime-types (2.99)
     mini_portile2 (2.0.0)
     minitest (5.8.4)
+    multi_json (1.11.2)
     nio4r (1.2.1)
     nokogiri (1.6.7.2)
       mini_portile2 (~> 2.0.0.rc2)
@@ -121,6 +125,7 @@ PLATFORMS
 DEPENDENCIES
   byebug
   factory_girl_rails
+  jbuilder
   pg
   puma
   rails (>= 5.0.0.beta2, < 5.1)
```

**Comment by schmijos** [comment]
There is a **workaround** for this issue. Defaulting the routes to the *JSON* format lets the problem disappear. After specifying the following in your *routes.rb* you can `render json: ...` explicitly again:

```ruby
defaults format: 'json' do
  resources :sensors
end
```

**Comment by anthonator** [comment]
In the event anyone is looking for an app to reproduce the problem: https://github.com/anthonator/rails_23923

Opened this issue with the Rails team:

https://github.com/rails/rails/issues/23923

**Comment by dsandber** [comment]
Doing an explicit render from the controller like this works:

render 'controller_name/action.json.jbuilder'

**Comment by rlugge** [comment]
Also having this issue.  It's something of a problem, because I need to `render json:` in testing the api controller via anonymous controllers.  There shouldn't _be_ a view in that scenario.

**Comment by spastorino** [comment]
Please, test this fix and let me know in any case.

**Comment by beydogan** [comment]
Having the same issue with rails **5.0.0.rc1**
