### ISSUE TITLE
Not returning a response body in JSON when testing RSPEC

### ISSUE THREAD

**Issue by kirkonrails** [rails/jbuilder#32]
Hi, 

I'm having trouble getting a response.body content when using jbuilder.. I'm not sure if this is an issue with jbuilder or an issue with me..  any help would be much appreciated

When testing a JSON response from an RSPEC controller test using JBuilder, my response.body is always "{}". It works fine in development/production modes when requested in the browser AND when I use the to_json method instead of jbuilder, I get proper JSON in my response.body

Anyone have a clue as to why my response.body would always be "{}" when testing?

----- Rspec/Debugger -------

it "should return the cart items via JSON", :focus do

get :index, :format => :json
end

(rdb:1) response.body

"{}"

**Comment by martinos** [comment]
Any one knows what to do in that case with `ActionController::TestCase` ? The `render_views` method doesn't work.

**Comment by louisscruz** [comment]
As of February 15, 2017, the solution by @mars still works for me!

**Comment by dimerman** [comment]
June 2018, @mars solution still solid 👍

**Comment by yzgan** [comment]
@mars solution is really working. Was able to enable it in controller test. 👍

**Comment by chibuezeayogu** [comment]
Hi, I am having an issue with `RSpec.describe "Department API", type: :request`
I have a `render :action, status: :ok` in an action in department controller and a view which matches the action in the view ie `views/departments/index.json.jbuilder` everything works fine but I am getting am error while testing it using `requests spec`

here  is the code
```
class DepartmentsController < ApplicationController
    def index
       @departments = Department.all
       render :index, status: :ok
    end
end
```


```
RSpec.describe "Department API", type: :request do
  let!(:department) { create(:department) }
  let(:params) do 
    { deparment: department.deparment_id }
  end
  
  describe "GET /departments" do
    context "when a user visits /departments path" do
      
      it "should return an array of departments" do
        get '/departments'

        expect(json).to eq department
      end
    end
  end
end
```
here is the error 
```
ActionView::MissingTemplate:
       Missing template departments/index, application/index with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :jbuilder]}.
```

**Comment by mayuresh-srivastava** [comment]
**render_views** does not for request specs?
