### ISSUE TITLE
No documentation recommending how to throw a 401 error

### ISSUE THREAD

**Issue by theovoss** [rails/jbuilder#320]
I'm new to rails and trying to figure stuff out. (doing it at work and I have some coworkers that know rails helping out)
I tried rendering a json payload with a 401 status code. Obviously this shouldn't try to render as the object associated with the route as it's an error, not an object.

The work-around my co-worker found was to define a jbuilder just for rendering errors:

```
  def render_unauthorized(payload = { errors: { unauthorized: ["You are not authorized perform this action."] } })
    @payload = payload.merge(response: { code: 401 })
    render template: '/api/v1/shared/errors', status: 401
  end
```

Raising the appropriate http status codes is (or at least should be) very common. Adding a few lines in the Readme suggesting how to do so would help others new to jbuilder/rails like me.

**Comment by georgeclaghorn** [comment]
This is beyond Jbuilder’s remit.
