### ISSUE TITLE
Usage with template outside of controller?

### ISSUE THREAD

**Issue by bf4** [rails/jbuilder#321]
The docs make it sound like JBuilder can be used, e.g. in a worker, without needing to rendering a controller action, but don't really describe the case.  Is it a first-level concern we can rely on?

without template, it would be something like the below, but get no caching advantage

``` ruby
require 'active_support/inflector'
require 'jbuilder'
result = Jbuilder.new do |json|
  json.title 'hello'
  json.content 'world'
end.attributes!
puts JSON.pretty_generate(result)
```

vs.

``` ruby
require 'jbuilder'
require 'jbuilder/template'
context = lookup_context # must respond to `controller.perform_caching`
template = JbuilderTemplate.new(context)
result = JbuilderHandler.call(template)
puts JSON.pretty_generate(result)
```

which seems pretty tightly coupled to the controller and won't work... so.. is it recommended then for a worker to do something like

``` ruby
renderer = ApplicationController.new
renderer.render_to_string('api/v1/users/_user', locals: {user: user})
```

**Comment by bf4** [comment]
any maintainers see this?  would appreciate at least a 'hi, we're busy right now'

**Comment by samsonnguyen** [comment]
+1. We are also running into an issue with this

**Comment by ksylvest** [comment]
With the standardization of `ApplicationController.render` it seems like this can be closed? Using:

**app/views/users/show.json.jbuilder**

```ruby
user = User.find(...)
ApplicationController.render(template: 'users/show', assigns: { user: user })
```

or

**app/views/users/_user.json.jbuilder**

```ruby
user = User.find(...)
ApplicationController.render(partials: 'users/user', locals: { user: user })
```

**Comment by bf4** [comment]
@ksylvest Though those examples work, they assume the controller render is calling jbuilder. I addressed that in my question

**Comment by georgeclaghorn** [comment]
If you want Action View features like caching, you need to go through a controller.

**Comment by bf4** [comment]
@georgeclaghorn Thanks for the partial answer, at least.  Would you accept a PR to the docs that using JBuilder cannot be used directly outside of a controller to get the same effect as in one?  Thought it's been a while, I did quite a bit of source diving at the time trying to figure it out.  It feels pretty icky to have a background job call 

```ruby
renderer = ApplicationController.new
renderer.render_to_string('api/v1/users/_user', locals: {user: user})
```
