### ISSUE TITLE
Generating partials in parallel

### ISSUE THREAD

**Issue by duffyjp** [rails/jbuilder#322]
I have a large feed which is quite expensive to build, however my server is a monster.  I would like to be able to generate caches for each object passed to my json partial in [parallel](https://github.com/grosser/parallel), then build my json feed as usual with 100% cache hits making it super fast.

Conceptually:
```ruby
# Pre-render and cache each expensive partial in parallel. 
Parallel.each(@people, in_processes: 16).do |person|
  json.warm_partial! 'wordpress_person', person: person
end

json.people @people do |person|
  # These are cached above so super fast.
  json.partial! 'wordpress_person', person: person
end
```

Has anyone done something like this?

**Comment by duffyjp** [comment]
I figured it out, and have been using this technique in production for a few days.  It works well.

## Controller
```ruby
  def index
    @people = Person.all

    Parallel.each(@people, in_processes: 16) do |person|
      person.cached_builder
    end
  end
```

## Model

```ruby
  def cached_builder
    Rails.cache.fetch(["json/", cache_key].join) do
      self.to_builder.target!
    end
  end

  def to_builder
    Jbuilder.new do |json|
      json.id   id
      json.name to_s
    end
  end
```

## View
```ruby
json.people @people do |person|
  json.person JSON.parse person.cached_builder
end
```

**Comment by awunder** [comment]
just a heads up for future googleists..this may cause unexpected behavior as it could serve wrong data. at least for me it turned out to totally screw up the json data.. as in sending wrong data out.

what i did instead was a:

`json.sections Parallel.map(@sections, in_processes: 3) { |section| JSON.parse(render 'instrument_report_sections/section', section: section) }`

in my view instead..

no caching, but still parallel processed

**Comment by duffyjp** [comment]
Wow! This is an old thread. @awunder what went wrong for you in terms of serving the wrong data?  Maybe you need to look at your cache key setup.  My approach does a just-in-time cache warmup in parallel and then sends the data without any threading.  It's still running to this day without issue.  

Does your approach suffer from any sorting issues (if that matters)?  That was one requirement I had, we had to return data in a specific order.

**Comment by awunder** [comment]
hey @duffyjp in my case it was like this:

1. there is a model `Instrument_report`
2. this model `has_many` `instrument_report_sections`
3. each of these sections needs to be rendered as a json partial
4. inside of such a section i have "layout defining" infos like number of columns for the frontend as well as chart data and what not

what happened was that this info got mixed up. one section was configured to be 6 columns wide but ended up being 12 or 10.. another section had symbol X with color Y defined for the chart but was rendered with symbol A and color B.. so, a total mix up

i agree, it sounds  a bit like a caching issue.. maybe one day i find the time to dig a little deeper
