### ISSUE TITLE
Option to remove question mark

### ISSUE THREAD

**Issue by marienfressinaud** [rails/jbuilder#323]
In Ruby, boolean attributes are often suffixed by a question mark (e.g. `editable?`). In JS, accessing an attribute with a question mark is possible only with bracket notation (e.g. `article['editable?']`. Since it makes more sense for me to use dot-style (e.g. `article.title`), I remove manually the question mark in the JBuilder view:

```ruby
json.extract! article, :id, :title
json.editable article.editable?

# But I would prefer to be able to write
json.extract! article, :id, :title, :editable?
```

Similarly to the `camelize: :lower` option, what do you think about adding a `question_mark: false` option to `Jbuilder.key_format`? (`true` by default)

**Comment by clamoris** [comment]
@marienfressinaud  jBuilder key formatter directly rely on ActiveSupport inflectors. As there are no 'remove question mark' method there I suggest you to just use something like this in jBuilder config:

`Jbuilder.key_format ->(key) { key.to_s.chomp('?')  }`

**Comment by marienfressinaud** [comment]
Elegant solution, it fits to my needs :)
