### ISSUE TITLE
ActionView 5 breaks #cache! with expires_in option

### ISSUE THREAD

**Issue by tnp** [rails/jbuilder#324]
With actionview 5.0.0.beta3, passing the expires_in option to the jbuilder cache! menthod, e.g.

```
json.cache! "cachekey", expires_in: 1.minute do
  json.name "Cache"
end
```
throws an ArgumentError:

```
unknown keyword: expires_in

Framework Trace
actionview (5.0.0.beta3) lib/action_view/helpers/cache_helper.rb:197:in `cache_fragment_name'
```
The problem seems to be that jbuilder passes the expires_in option to #cache_fragment_name, which has been rewritten to take keyword arguments and no longer accepts options other than skip_digest and virtual_path:

```
def cache_fragment_name(name = {}, skip_digest: nil, virtual_path: nil)
```

It can be fixed by filtering the options within the definition of #cache!, e.g. replace

```
value = ::Rails.cache.fetch(_cache_key(key, options), options) do
```

with

```
name_options = options.slice(:skip_digest, :virtual_path)
value = ::Rails.cache.fetch(_cache_key(key, name_options), options) do
```

**Comment by courtsimas** [comment]
:+1:

**Comment by alpaca-tc** [comment]
👍
