### ISSUE TITLE
Rails 5 beta 3 caching issue

### ISSUE THREAD

**Issue by noiseunion** [rails/jbuilder#331]
whenever I try using `json.cache!` in my jbuilder templates i am getting the following error:

```ruby
#<ActionView::Template::Error: undefined method `perform_caching' for #<Rdc::V1::Promoters::TextBlocksController:0x007feebc05ac50>>
```

I have combed through everything and all appears to be setup correctly.  I am in API Only mode.  Has anyone else dealt with this issue?  Any suggestions on where else I could look for maybe some off config?

**Comment by noiseunion** [comment]
Just as a quick update, I added the following to my base controller based on what I found here: [rails issue #17657](https://github.com/rails/rails/issues/17657#issuecomment-71385191):

```ruby
def perform_caching
    Rails.configuration.action_controller.perform_caching
end
```

After doing so I now see the following new error message:

```ruby
#<ActionView::Template::Error: undefined local variable or method `view_cache_dependencies' for #<#<Class:0x007feeb5f8b870>:0x007feeb5f8a1c8>>
```

I am not sure if this is an issue with JBuilder or Rails I guess since it appears as though some dependency may not actually be getting loaded correctly, but I can't seem to find anyone else seeing the same behaviors.

**Comment by noiseunion** [comment]
Well it looks like this is a Rails issue so I will close this.  I was able to resolve it after digging through Rails.  It would appear that ActionController::API does not include ActionController::Caching by default so after I added that to my base controller everything started working again.

**Comment by prikha** [comment]
For the history: I ended up with`ActionController::Caching` included into api base controller inherited from `ActionController::API`. And was still getting the same error. It occurs that modules included into my base controller were in the wrong order. 
Caching required Helpers to be required before hand like so:

```
include ActionController::Helpers
include ActionController::Caching
```

**Comment by arg** [comment]
I got the same issue on Jbuilder 2.9.1 / Rails 5.2.3 (API mode). As a workaround, included `ActionController::Caching` to the base API controller:

```ruby
class ApplicationController < ActionController::API                                                    
  include ActionController::Caching # https://github.com/rails/jbuilder/issues/331
  # ...
end
```
