### ISSUE TITLE
Rails 5 Deprecation warning - `Mime::JSON`

### ISSUE THREAD

**Issue by shadowed87** [rails/jbuilder#345]
I haven't checked if this is the case with the master branch, but after upgrading to Rails 5 I get the following message: 

`
DEPRECATION WARNING: Accessing mime types via constants is deprecated. Please change `Mime::JSON` to `Mime[:json]`. (called from <class:JbuilderHandler> at /usr/lib/ruby/gems/2.3.0/gems/jbuilder-1.5.3/lib/jbuilder/jbuilder_template.rb:110)
`

**Comment by rwz** [comment]
You're using JBuilder 1.5.3 which very old and doesn't even have Rails 5 support. The most recent version is 2.6.0
