### ISSUE TITLE
Send list of selected attributes to partial?

### ISSUE THREAD

**Issue by philbattos** [rails/jbuilder#347]
Is it possible to send a list of attributes to a partial and create custom values for those attributes?

For example, let's say that i have this partial:

``` ruby
# app/views/messages/_message.json.jbuilder

json.title message.title
json.content message.content
json.author message.author.name
```

I can call the partial with: 

``` ruby
json.partial! 'messages/message', message: message
```

But what if i only want to render some of the attributes in the partial? If i just want the title and content, i could skip the partial and use `json.(messages, :title, :content)` but this doesn't work for the author because the author's value comes from a different model `message.author.name`. So i would like to call the partial with something like this:

``` ruby
json.partial! 'messages/message', message: message, :title, :author
```

where `:title, :author` is a list of attributes that will be rendered by the partial. If an attribute is not in the list, it wouldn't be rendered by the partial. Is this possible?

**Comment by abhiQmar** [comment]
you can define a `author_name` method in your message class and use `json.(messages, :title, :content, :author_name)` syntax.

You can use an if condition at the end of the line `json.author message.author.name` to conditionally add it to the response.

**Comment by philbattos** [comment]
Thanks @abhiQmar. Those solutions work if the message object only has a few attributes but it can get ugly if the message object has many attributes because we would have to put an if condition at the end of every line of json:

```
json.title message.title if requested_attributes.include?(:title)
json.content message.content if requested_attributes.include?(:content)
json.author message.author.name if requested_attributes.include?(:author)
.....
```

You can see how this could become a cumbersome way of rendering selected attributes if the object had many fields. Likewise, if we created methods in the message class to hold the conditionals, we would have to create a method for each attribute, which seems like a lot of extra rendering logic code. It seems like the rendering library (jbuilder) should be able to handle this scenario more gracefully. 

Any other ideas?

**Comment by georgeclaghorn** [comment]
Nope, sorry.
