### ISSUE TITLE
character '-' on attribute name

### ISSUE THREAD

**Issue by djmaxisauce** [rails/jbuilder#356]
I am migrating an api from php to rails.
php json attributes has the format 'content-id' , 'category-id', with '-'

now, with jbuilder i want to return a json, for example:

json.content-id "234"

The '-' makes a syntax error on the .jbuilder file. Are there any way to make this ? 

thx

**Comment by rwz** [comment]
```ruby
Jbuilder.key_format -> (key) { key.tr(?_, ?-) }
```
