### ISSUE TITLE
Question: Update cached template if reference/association changed

### ISSUE THREAD

**Issue by knobsam** [rails/jbuilder#368]
Hi,

I have a small problem with caching jbuilder templates.
My use case: I have the models "SlideSet" and "Slide". SlideSet has a reference to Slide (active_slide). I updated my templates to use "json.cache!":
```
json.cache! @slide_set do
  json.partial! 'slide_set', slide_set: @slide_set
end
```
Works fine for SlideSet and updates on every attribute of this model. But it does not work for an update on "active_slide" reference.
Is there a possible way to also check the references SlideSet has for an update and revalidate/update the cached template afterwards if necessary?

Thanks for your help!

**Comment by frodsan** [comment]
I guess you can do:

```
json.cache! @slide_set, @slide_set.active_slide do
  # ...
end
```
