### ISSUE TITLE
Rails generate model breaks with jbuilder related error

### ISSUE THREAD

**Issue by prowler** [rails/jbuilder#371]
Hey guys,

I stumbled upon an issue while generating models for a fresh new rails project.
```
$ rails g model somemodel
/***/***/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.2/lib/thor/parser/option.rb:130:in `validate_default_type!': An option's default must match its type. (ArgumentError)
```
I'm using:
```
Using rails 5.0.0.1
Using jbuilder 2.6.0
Using thor 0.19.2
```

What I found is that it is something related to `jbuilder` gem. When I remove it from Gemfile the rails generator works.
It fails at:
```
/***/***/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.2/lib/thor/parser/option.rb:130
```
And a quick debug on line 129 in this file shows:
```
default_type = :boolean
@type = :string
@name = "jbuilder"
```

I'm not sure if it is `jbuilder`, `rails` or `thor`. I hope that you can help me debug this.

**Comment by rafaelfranca** [comment]
It is a thor bug https://github.com/erikhuda/thor/issues/533

**Comment by prowler** [comment]
Thanks @rafaelfranca That was quick :)

**Comment by sferik** [comment]
Pushing a fix to `thor` now. Sorry for the trouble.
