### ISSUE TITLE
Warning messag Expected string default value for '--jbuilder'; got true (boolean)

### ISSUE THREAD

**Issue by Jojoooo1** [rails/jbuilder#373]
Hi, 

When I am creating a new rails project, and try to generate a migration or a controller I am encounterting those error message : 

Expected string default value for '--test-framework'; got false (boolean)
Expected string default value for '--jbuilder'; got true (boolean)

When I removed the gem Jbuilder its not showing anymore. 

Any leads ?

Thanks in advance.
Joanthan.

**Comment by rafaelfranca** [comment]
It was a bug in Thor. Make sure you have the most updated version
