### ISSUE TITLE
Jbuilder not rendering view in rails API after device install

### ISSUE THREAD

**Issue by IvRRimum** [rails/jbuilder#377]
It was working before. But after i installed devise and simple_token_authentication, it just shows blank page.

Heres what rails logs show:
```
Started GET "/home.json" for 85.254.182.95 at 2017-01-15 15:03:51 +0200
Processing by HomeController#index as JSON
Completed 200 OK in 0ms (Views: 0.1ms | ActiveRecord: 0.0ms)


Started GET "/home.json" for 85.254.182.95 at 2017-01-15 15:05:24 +0200
Processing by HomeController#index as JSON
Completed 200 OK in 1ms (Views: 0.1ms | ActiveRecord: 0.0ms)
```

I have a view in `views/home/index.json.jbuilder` ( i tryed renaming it to `index.jbuilder` ).
I tryed to `render "home/index.json.jbuilder"`, i tryed using `respond_to ...`

My gemfile:
```
source 'https://rubygems.org'

gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
gem 'sqlite3'
gem 'puma', '~> 3.0'
gem 'jbuilder', github: 'rails/jbuilder'
gem 'dotenv-rails'
gem 'devise'
gem 'simple_token_authentication', '~> 1.0'

group :development, :test do
  gem 'byebug', platform: :mri
  gem 'pry'
end

group :development do
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

if i remove simple_token_authentication jbuilder is working again. Whats the problem?

How to fix this issue?

**Comment by robin850** [comment]
This doesn't seem to be a problem with Jbuilder at all but rather with `simple_token_authentication` that adds [a `before_filter`](https://github.com/gonzalo-bulnes/simple_token_authentication/blob/2ea7d13e155bf7d7da22a69e3e884e94d05a8dae/lib/simple_token_authentication/token_authentication_handler.rb#L157-L162) that get executed before your action get called. If you don't provide a valid token, then you won't be able to access any resource.

Thanks for reporting this anyway !
