### ISSUE TITLE
Weird bug: jbuilder render HTML with the json inside

### ISSUE THREAD

**Issue by tchret** [rails/jbuilder#384]
Hi,

I'm facing a strange issue, the json generated by jbuilder is rendered inside my `application.slim` structure. 

![image](https://cloud.githubusercontent.com/assets/4539476/22898548/ffecf9f8-f227-11e6-98a0-ab1c391d7c04.png)

Maybe I'm totally wrong and the problem is not coming from jbuilder, just in case...

**Comment by rafaelfranca** [comment]
Does it happen if you rename `application.slim` to application.html.slim`?

**Comment by tchret** [comment]
@rafaelfranca 🤘 it worked. Well seen, thanks for the super-fast answer. 

do you know why?

**Comment by rafaelfranca** [comment]
If you not specify the content type it will be used to all responses, html, json, javascript, csv, etc. This is why Rails generates application.html.erb.

**Comment by tchret** [comment]
@rafaelfranca got it. thanks again
