### ISSUE TITLE
Missing documentation for option `as:`

### ISSUE THREAD

**Issue by justin808** [rails/jbuilder#385]
It seems that the documentation for `as` could be as follows:

> The `as: :some_symbol` is used with partials. It will take care of mapping the passed in object to a variable for the partial. If the value is a collection (either implicitly or explicitly by using the `collection:` option, then the each value of the collection is passed to the partial as the variable `some_symbol`. If the value is a singular object, then the object is passed to the partial as the variable `some_symbol`.

This documentation could go around this section:

---------------------

You can use partials as well. The following will render the file
`views/comments/_comments.json.jbuilder`, and set a local variable
`comments` with all this message's comments, which you can use inside
the partial.

```ruby
json.partial! 'comments/comments', comments: @message.comments
```

It's also possible to render collections of partials:

```ruby
json.array! @posts, partial: 'posts/post', as: :post

# or

json.partial! 'posts/post', collection: @posts, as: :post

# or

json.partial! partial: 'posts/post', collection: @posts, as: :post

# or

json.comments @post.comments, partial: 'comments/comment', as: :comment
```

**Comment by justin808** [comment]
I will submit a PR if appropriate.

**Comment by rafaelfranca** [comment]
Seems good to me. Could you send the PR?

**Comment by justin808** [comment]
Hi @rafaelfranca, would you like me to document this as well:

https://forum.shakacode.com/t/how-to-have-jbuilder-return-a-hash/772/1

You may get into a situation where you'd rather get the Hash from jBuilder rather than a string of JSON.

For example, you might normally get the JSON string like this in your controller method:

```ruby
   data = render_to_string(
        template: "/api/v1/comments/show.json.jbuilder",
        locals: { comment: @comment},
        format: :json
      )
```

And the `show.json.jbuilder`

```rb
json.partial! "/api/v1/comments/comment.json.jbuilder", comment: @comment
```


You could instead do this:

```ruby
    data_hash = JbuilderTemplate.new(view_context) do |json|
      json.partial! "/api/v1/comments/comment.json.jbuilder", comment: @comment
    end.attributes!

    json = data_hash.to_json
```

Notice for the 2nd one:

1. We're rendering a partial, and setting the value of the local variable comment, as is done for the `show.json.jbuilder` view.
2. `attributes!` converts the object into the Hash. Then calling `to_json` on the Hash will convert it back to json.

The results are not going to be 100% identical as some empiracal results show that Jbuilder render_to_string will round off decimals at 10 digits, whereas calling `data_hash.to_json` gave us 13 digits of precision.

If you need to combine the result of several Jbuilder partials, then this technique to get a Hash should be quite useful. For example, you can combine the hashes and create a new result.

```ruby
hash = JbuilderTemplate.new(viewContext) do |json|
  json.partial! "/path/to/partial", local_var: local_var_value
end.attributes!
```

**Comment by rafaelfranca** [comment]
That is too much internals to the users and I'd prefer to not document it. The difference of behavior with rounding is another reason to not do.

**Comment by justin808** [comment]
@rafaelfranca:

1. is `attributes!` (or some other mechanism for getting a Hash) supported?
2. My use case is that I need to combine the results of several partials dynamically. Is it OK to render to a Hash, then combine the hashes, and call `to_json`? Or maybe the code should dynamically create a Jbuilder template from several partials? And call render_to_string on that?

cc: @robwise

**Comment by justin808** [comment]
@rafaelfranca 

* Can we get #386 merged?
* How about this instead of using `.attributes!`

https://forum.shakacode.com/t/how-to-have-jbuilder-return-a-hash/772/3?u=justin

```ruby
 builder = Jbuilder.new do |props|
  props.lessons do
     props.partial! "api/v1/lessons/_lesson_list.json.jbuilder", 
                            lessons: @lessons}
  end
  props.courses do
     props.partial! "api/v1/courses/_course_list.json.jbuilder",
                           courses: @courses
  end
end
json = builder.target!
```

Target is defined [here](https://github.com/rails/jbuilder/blob/8911c05e4181e59066f9805cbd87eac1893bfc7c/lib/jbuilder.rb#L249).

**Comment by robwise** [comment]
I assume because it's not the intended use case to be using jbuilder outside of views?

**Comment by justin808** [comment]
@robwise I mean more of a general doc question. It would be nice to have all the methods documented.

**Comment by justin808** [comment]
@rafaelfranca Do you want to merge this?

**Comment by jeremy** [comment]
#386
