### ISSUE TITLE
NO format_content function

### ISSUE THREAD

**Issue by webchi** [rails/jbuilder#396]
There is example in README

> json.content format_content(@message.content)

But that fuction not emplemented. How could I output raw html code? .html_safe not working

**Comment by djones** [comment]
I found this confusing too.

**Comment by djones** [comment]
`format_content` shows in a bunch of sample code. E.g. https://www.leighhalliday.com/responding-with-json-in-rails and https://til.codes/active-model-serializer-vz-jbuilder-vz-rabl-vz-grape-entity-vz-roar/

Did this method used to exist and now has been removed?

**Comment by djones** [comment]
I checked out the `1.x-stable` branch. Which is 3-4 years old and includes the `format_content` example in the readme and that method doesn't exist back then either. The readme should probably be cleaned up to remove calls to methods that don't exist.

`html_safe` does not take effect for me like @webchi is reporting. How is one supposed to render raw HTML as a value in a jbuilder response?

**Comment by webchi** [comment]
Thats ok with html output. It just encoded and looks good in the browser.
But README should be fixed.

**Comment by rlue** [comment]
It's puzzling. The second time it appears in the README, it's preceded by the following comment:

```
# Any helpers available to views are available to the builder
json.content format_content(@message.content)
```

At first, this made me think that `format_content` is a Rails ActionView helper method that I just hadn't heard of yet, _à la_ `link_to`, but I'm [pretty confident](https://www.google.com/search?q=site:api.rubyonrails.org+"format_content") that's not the case.

+1 for changing this to something else in the docs, or just removing it altogether.

**Comment by georgeclaghorn** [comment]
It’s an example of a helper you may have defined in your app. Please open a PR if you have a better idea. 😄
