### ISSUE TITLE
Readme recommends broken version of jbuilder_cache_multi gem

### ISSUE THREAD

**Issue by markwpiper** [rails/jbuilder#399]
README.md says "If you are rendering fragments for a collection of objects, have a look at jbuilder_cache_multi gem. It uses fetch_multi (>= Rails 4.1) to fetch multiple keys at once."

Unfortunately the current version of this gem has a critical bug (see https://github.com/yonahforst/jbuilder_cache_multi/issues/17)

Please recommend using this gem only from github master until the bug fix has been released.
gem 'jbuilder_cache_multi', github: 'yonahforst/jbuilder_cache_multi', branch: 'master'

**Comment by dhh** [comment]
I trust that @yonahforst will soon be able to push out a fresh release to get this resolved 👍

**Comment by yonahforst** [comment]
just pushed

**Comment by dhh** [comment]
❤️

**Comment by dhh** [comment]
BTW, I'd love to see multifetch collection handling added to Jbuilder. I've just pushed a 2.7.0 release that now requires Rails 4.2+, so it should be possible. I'd prefer if we didn't need a new method for it, though. Think that's possible? Something you're interested in working on? Thanks again!
