### ISSUE TITLE
Weird error reporting when an error occur in a JBuilder partial

### ISSUE THREAD

**Issue by Sephi-Chan** [rails/jbuilder#40]
Hi,

I noticed two errors in the reporting of errors with jbuilder partials rendered from a view.
The first is weird but not a big deal, the second is really problematic for debugging.

I have a view and two partials.

In `views/application/home.html.haml`, I have:

``` ruby
- json = render(partial: 'users/user', formats: [:json], locals: { user: @user })
= javascript_tag { "window.data = {}; window.data = #{raw(json)};" }
```

In `views/users/_user.html.haml`, I have:

``` ruby
= user.undefined_method_called_from_haml_template
```

In `views/users/_user.json.jbuilder`, I have:

``` ruby
json.name user.undefined_method_called_from_jbuilder_template
```

Displaying the page raises:

> NoMethodError in Application#home
> Showing ~/MyTest/app/views/users/_user.html.haml where line # raised:
> undefined method `undefined_method_called_from_jbuilder_template' for #User:0x007fb2bea96de8

The reported file is wrong: it should be the JSON version.

So now, the second error is visible when there is no other version of the same partial (in my case, by removing `_user.html.haml`).

> ActionView::MissingTemplate in Application#data
> Showing ~/MyTest/app/views/application/home.html.haml where line #1 raised:
> Missing partial users/user with {:locale=>[:en], :formats=>[:html], :handlers=>[:erb, :builder, :jbuilder, :coffee, :haml]}.

What the hell? Why does any errors occurring in the partial are ignored and reported as a missing template (plus, the `formats` and `handlers` are not correct?
If I fix the error (not easy with this weird report) in the template, it works!

Any idea?

**Comment by earnold** [comment]
I am seeing this again in rails 3.2.21 - is there any known workaround?

**Comment by earnold** [comment]
I've created a small demo app to precisely demonstrate the problem: https://github.com/earnold/error-demo

When there is an error in the jbuilder template, you get a missing template error. The real error vanishes.

**Comment by yuki24** [comment]
@earnold Rails 3.2 is no longer maintained. You should upgrade to 4.1 or higher.

**Comment by earnold** [comment]
@yuki24 - unfortunately, I'm trying to use this in a large app and it would be prohibitively difficult to upgrade rails. I guess I was hoping that since this issue had surface with earlier versions of 3.2 with Jbuilder, there would be a know fix.

**Comment by brettfishman** [comment]
@earnold I've also run into this issue in the past. I'm not a big fan of monkey patches, but this one to ActionView::Template will surface the original error. Just put it in an initializer, and you should be good.

```
if Rails.env.development?
  module ActionView
    class Template

      protected

      def handle_render_error(view, e) #:nodoc:
        if e.is_a?(Template::Error)
          e.sub_template_of(self)
          raise e
        else
          assigns  = view.respond_to?(:assigns) ? view.assigns : {}
          template = self
          unless template.source
            # If an error occurs while the Jbuilder template is being rendered, 
            # this block of code would raise a false exception (ActionView::MissingTemplate) 
            # and swallow the original error. This monkey patch wraps the first exception
            # in a begin/rescue/ignore block so the original exception can bubble up.
            begin
              template = refresh(view)
              template.encode!
            rescue Exception => ignore; end
          end
          raise Template::Error.new(template, assigns, e)
        end
      end

    end
  end
end
```

**Comment by rwz** [comment]
If you're still on Rails 3.2 I suggest to instantiate a new view context each time you need to render a jbuilder view into an HTML view.

Somewhat like this:

```ruby
def render_with_next_context(*args)
  context = ApplicationController.new.view_context
  context.render(*args)
end
```

and then in your HAML/Erb template:

```haml
- json = render_with_new_context(partial: 'users/user', formats: [:json], locals: { user: @user })
= javascript_tag { "window.data = #{raw(json)};" }
```

This is probably far from being the most effective way of doing it, but just something from the top of my head.

**Comment by earnold** [comment]
@rwz and @brettfishman  - thank you both so much for the help! I was banging my head against this for ages. 

I've implemented the monkeypatch for now. In the second case, using the new context, gave me this error `ActionView::Template::Error (undefined method `host' for nil:NilClass):` when I called url helpers.

**Comment by earnold** [comment]
I know I'm beating a dead horse at this point, but...

@brettfishman  - I found I could get a more accurate stack trace by using this monkey patch: 

```
if Rails.env.development? || Rails.env.staging?
  module ActionView
    class Template

      protected

      def handle_render_error(view, e) #:nodoc:
        if e.is_a?(Template::Error)
          e.sub_template_of(self)
          raise e
        else
          assigns  = view.respond_to?(:assigns) ? view.assigns : {}
          template = self
          # If an error occurs while the Jbuilder template is being rendered in 
          # in a nested context, you have a mismatch between the template format
          # and the view context. Therefore, this block of code would raise 
          # a false exception (ActionView::MissingTemplate) and swallow the original 
          # error. This monkey patch tricks rails into thinking it was a json request
          # so that refreshing the source hits the right partial
          if template.formats == [:json]
            view.lookup_context.formats = [:json]
          end
          unless template.source
            template = refresh(view)
            template.encode!
          end
          raise Template::Error.new(template, assigns, e)
        end
      end

    end
  end
end
```
