### ISSUE TITLE
How to prevent double-rendering of a partial

### ISSUE THREAD

**Issue by AlexVPopov** [rails/jbuilder#401]
Sorry for posting a how-to question here, but since nobody has answered [this SO question](https://stackoverflow.com/questions/27245020/how-can-i-render-one-partial-twice-in-jbuilder) I thought there's no point in asking there again.

So the idea is - if two fields in the json need to contain the result of the same rendering of a partial, is there a way of rendering once and then embedding twice.

So instead of:

```ruby
json.foo do |json|
  json.partial! 'baz', baz: baz
end
json.bar do |json|
  json.partial! 'baz', baz: baz
end
```

can something like this be done:

```ruby
rendered_baz = render partial: 'baz', baz: baz

json.foo rendered_baz
json.bar rendered_baz
```
?

Sorry again for posting a how-to here.

**Comment by gihnius** [comment]
Why not just cache the partial?

**Comment by AlexVPopov** [comment]
@gihnius could you tell me how to do that?

**Comment by gihnius** [comment]
@AlexVPopov 

Sth. like:

in partial baz(_baz.json.jbuilder)

``` ruby
json.cache baz.cache_key do
  # sample
  json.extract! baz, :key1, :key2 ...
end
```

Not sure if I misunderstood you :)

**Comment by AlexVPopov** [comment]
@gihnius I'll try that, thank you.

**Comment by AlexVPopov** [comment]
As I cannot determine when I'll be able to provide feedback, I'm closing the issue. I'll reopen it, if I come to this at a later point. Thank you for the advice.
