### ISSUE TITLE
Need for a full documentation

### ISSUE THREAD

**Issue by pr-201** [rails/jbuilder#407]
Where I can find full documentation with examples of jbuilder, readme file of this repository is too small and don't give understanding of functionality. I need to make with it next json-configuration:
`{
  "crossover" : {
    "elements" : { 
      "bb" : {
        "title": "bumper",
        "code:: "bb"
      },
      "trunk" : {
        "title": "trunk",
        "code:: "trunk"
      }
    }
  },
  "hatchback" : {
    "elements" : { 
      "bb" : {
        "title": "bumper",
        "code:: "bb"
      },
      "trunk" : {
        "title": "trunk",
        "code:: "trunk"
      }
    }
  },
  "sedan" : {
    "elements" : { 
      "bb" : {
        "title": "bumper",
        "code:: "bb"
      },
      "trunk" : {
        "title": "trunk",
        "code:: "trunk"
      }
    }
  }
}`

Maybe have a links, samples and etc, using jBuilder in rails 5.1.2

**Comment by rafaelfranca** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
