### ISSUE TITLE
How to escape html globally on a json.jbuilder file

### ISSUE THREAD

**Issue by rclakmal** [rails/jbuilder#408]
In the following ` json.jbuilder` response, html values have been escaped using the `h `method. However, is there a global setting we could do in jbuilder, in order to escape html in all values without having to explicitly put it inside a `h `call

```
json.data do
  json.name  h(@student.name)
  json.comment h(@student.comment)
end
```

**Comment by georgeclaghorn** [comment]
There’s no such setting, sorry.
