### ISSUE TITLE
Bad propagation of format with partial! when using render

### ISSUE THREAD

**Issue by Sephi-Chan** [rails/jbuilder#41]
I use a JBuilder template in a view to seed data to the Javascript side of the application.

To do so, I use a line like:

``` ruby
json = render(partial: 'users/user', formats: [:json], locals: { user: current_user })
```

Then, in my `_user.json.jbuilder` template, I have:

``` ruby
json.partial! 'vehicles/attribute', attribute: attribute
```

It doesn't work.

Due to the weird error reporting of JBuilder (see https://github.com/rails/jbuilder/issues/40), I can't see the real reason but I managed to have the real error message (by creating a dumb `_user.html.haml` template):

> Missing partial vehicles/attribute with {:locale=>[:fr], :formats=>[:html], :handlers=>[:erb, :builder, :jbuilder, :coffee, :haml]}.

As you can see, depsite the fact that I render the JSON version of my current_user template, JBuilder looks for the HTML version.

To get it working, I have to specify the format in the partial name:

``` ruby
json.partial! 'vehicles/attribute.json', attribute: attribute
```

But it provoques the deprecation warning:

> DEPRECATION WARNING: Passing the format in the template name is deprecated. Please pass render with :formats => [:json] instead. (called from partial! at /home/foo/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/bundler/gems/jbuilder-e2a66168bfa3/lib/jbuilder_template.rb:18)

Note that passing a `:formats` option to `partial!` doesn't work neither.

Thanks!

**Comment by vedmant** [comment]
I have the same issue:

This doesn't work:
json.posts list.posts.order('created_at DESC'), partial: 'jbuilders/post', as: :post

And this works:
json.posts list.posts.order('created_at DESC'), partial: 'jbuilders/post.json.builder', as: :post

**Comment by ryanb** [comment]
This has resurfaced for me in Rails 6. Passing the `formats: [:json]` option is necessary otherwise I get the missing template error.

> json.posts list.posts.order('created_at DESC'), partial: 'jbuilders/post.json.builder', as: :post

Including the extension has a couple unwanted side effects:
* Relative locales do not lookup the template path correctly (it includes the extension).
* The fragment cache key includes the `json.jbuilder` extension. If you render the partial a different way elsewhere it will generate two caches since they have a different key.
