### ISSUE TITLE
. in jbuilder attribute name

### ISSUE THREAD

**Issue by AliAdnanSohail** [rails/jbuilder#410]
I am using JBuilder in Rails.
I need to create a service for datatables that contains an attribute with name like 'users.site'
but whenever i write json.users.site user.name it gives me error 'undefined method `site' for nil:NilClass'

Here is the link for sample response that datatable expect: http://imgur.com/a/PziXB
Datatable json link : https://editor.datatables.net/examples//php/join.php

**Comment by bakku** [comment]
Have you tried

`json.set! "users.site", user.name`

**Comment by robin850** [comment]
Thanks for your answer @bakku, you're right !
