### ISSUE TITLE
Is "except attributes" an anti-pattern?

### ISSUE THREAD

**Issue by chenqingspring** [rails/jbuilder#414]
I have some special use case on `extract!`method. Sometimes, I need render all attributes, or almost all attributes.

I googled some solution like: [how-to-extract-all-attributes](https://stackoverflow.com/a/23422260/2091375) and [is-there-any-way-to-hide-attributes](https://stackoverflow.com/a/38316008/2091375) which are perfectly matched my special requirement.

But all the solutions seems not elegant to me, so I create [jbuilder-except](https://github.com/chenqingspring/jbuilder-except) gem, providing api `except!`, which have a reverse function of `extract!`

So far, the only thing I feel uncomfortable is, I have to check model to understand what attributes  will be rendered. I'm not sure if this kind of use case is an anti-pattern ?

**Comment by georgeclaghorn** [comment]
Please use the [rubyonrails-talk](https://groups.google.com/forum/#!forum/rubyonrails-talk) mailing list or other fora for usage questions and code feedback requests, where a wider community will be able to help you. We reserve the issue tracker for issues.
