### ISSUE TITLE
Compressing JBuilder Output

### ISSUE THREAD

**Issue by leoyoon** [rails/jbuilder#426]
Hi, part of my program generates a JSON file using JBuilder and then renders it in a view.
What I would like to do is zip or compress the JSON output made by JBuilder and then download the given zip  file. Is there any way I can achieve this at the moment?

**Comment by georgeclaghorn** [comment]
Sorry, there’s no way to do that with Jbuilder alone. You can look into using [https://github.com/rubyzip/rubyzip](RubyZip) to archive a JSON file that you generate using Jbuilder.
