### ISSUE TITLE
Deprecation warnings about fragment caching in Rails 5.2.0.rc1

### ISSUE THREAD

**Issue by conzett** [rails/jbuilder#427]
JBuilder version 2.7

```
DEPRECATION WARNING: Calling fragment_cache_key directly is deprecated and will be
removed in Rails 6.0. All fragment accessors now use the combined_fragment_cache_key
method that retains the key as an array, such that the caching stores can interrogate
the parts for cache versions used in recyclable cache keys.
```

Looks like this may be a result of the [Recyclable cache key work](https://github.com/rails/rails/pull/29092). Not sure if a JBuilder release is set to coincide with 5.2 or not.

**Comment by jujulisan** [comment]
My application use version 2.7.0 and receive the warning.

**Comment by czj** [comment]
Having a release would be really nice, we are still using a commit hash in our Gemfile :(

**Comment by MrEmelianenko** [comment]
+1

**Comment by erikthiem** [comment]
I'm also running into this. Any updates?
