### ISSUE TITLE
undefined local variable or method `json` for #<#<Class:...

### ISSUE THREAD

**Issue by euricovidal** [rails/jbuilder#433]
always when I try start a new `rails new test_api --api` and use a jbuilder template, I had the same error:
```
ActionView::Template::Error (undefined local variable or method `﻿json' for #<#<Class:0x007fb00b243de0>:0x007fb00b233cb0>
Did you mean?  json
               JSON):
    1: ﻿json.anything '123'

app/views/users/index.json.jbuilder:1:in `_app_views_users_index_json_jbuilder___2818099992439133559_70197034158660'
```

My Gemfile
```
source 'https://rubygems.org'

gem 'rails', '~> 5.1.4'
gem 'sqlite3'
gem 'puma', '~> 3.7'
gem 'jbuilder', '~> 2.5'

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
```

The controller has just the empty action and view has a static value
`app/users/index.json.jbuilder'
```
json.anything ' 123'
```

I put all files in the repo https://github.com/euricovidal/test_api_with_jbuilder_error
log https://github.com/euricovidal/test_api_with_jbuilder_error/blob/master/log/development.log

I had try check all configs, but the error no make sense 😅 

My OS is mac osx, but I try on docker and had the same error 😞

**Comment by euricovidal** [comment]
I'm sorry, I do not know what's realy happen but the problem is on the editor, when I create the `.json.jbuilder` file using `vim` this error occurs, but when I create it using the `sublime` everything works fine, sorry. 😅

**Comment by robin850** [comment]
Trying to clone your application, I can reproduce the error but the message is slightly more relevant going to `/users.json`:

~~~
"#<ActionView::Template::Error: undefined local variable or method `\ufeffjson' for #<#<Class:0x00007f98bc888d38>:0x00007f98b9a029a0>\nDid you mean?  json\n               JSON>"
~~~

It looks like it's effectively a misconfiguration of your Vim that adds a [byte order mark](https://en.wikipedia.org/wiki/Byte_order_mark) to the file ; the error went away by removing the file and recreating it.

Thanks for reporting this anyway, we can give this a close.
