### ISSUE TITLE
`Jbuilder.key_format camelize: :lower` does not transform nested object keys

### ISSUE THREAD

**Issue by ademars94** [rails/jbuilder#434]
I have this line in my environment file: `Jbuilder.key_format camelize: :lower`.

In my app, there's a many to many relationship between `foos` and `bars`

In my `_foo.json.jbuilder` file, I have the following:
```
json.extract! foo, [:id, :foo_name, :bars]
json.url foo_url(foo, format: :json)
```

The json is returned as follows:
```
{
  "id": 1,
  "fooName": "foo", // camelcase in first level
  "bars": [
    {
      "id": 1,
      "bar_name": "bar" // snake_case in nested obj, bad
    }
  ]
}
```

When I tell Jbuilder I want it to change my keys to lower camel case, it should work on nested objects.  This seems like a bug.

**Comment by ademars94** [comment]
I have solved this issue by using the partial view for the nested object.

The code now looks like this:

```
json.extract! foo, [:id, :foo_name]

json.bars foo.bars, partial 'bars/bar', as: :bar

json.url foo_url(foo, format: :json)
```

And it is returning this: 

```
{
  "id": 1,
  "fooName": "foo", // camelcase in first level
  "bars": [
    {
      "id": 1,
      "barName": "bar" // camelcase in second level!
    }
  ]
}
```

**Comment by MSchmidt** [comment]
Your solution should be considered a workaround. This is still a bug. All keys should be transformed.

**Comment by pduey** [comment]
> Your solution should be considered a workaround. This is still a bug. All keys should be transformed.

Agreed. Smells like a bug. Note, the work around is not to create a partial, but to list out keys individually. So, when rendering a collection, instead of letting jbuilder inspect the objects for their attributes, you have to list the attributes explicitly. Rather than create the partial, you could do:

```
json.bars foo.bars do |bar|
  json.(bar, :id, :bar_name)
end
```
and the keys will be camelCased (assuming that is your format)

**Comment by wileybaba** [comment]
Any update on this bug?

**Comment by akshayKhot** [comment]
Jbuilder now supports deep formatted keys. From the [readme](https://github.com/rails/jbuilder),

> By default, key format is not applied to keys of hashes that are passed to methods like set!, array! or merge!. You can opt into deeply transforming these as well:

```
json.key_format! camelize: :lower
json.deep_format_keys!
json.settings([{some_value: "abc"}])

# => { "settings": [{ "someValue": "abc" }]}
```

You can set this globally with the class method deep_format_keys (from inside your environment.rb for example):

```
Jbuilder.deep_format_keys true
```

However, I've noticed that even after enabling this setting, keys that were nested more than three-level deep were not converted to camelCase. For example, notice the keys `start_date` and `end_date` in the example below. 

```
{
    "payrollReport": {
        "employeeReports": [
            {
                "employeeId": 1,
                "payPeriod": {
                    "start_date": "2020-01-01",
                    "end_date": "2020-01-15"
                },
                "amountPaid": "600.0"
            },
            {
                "employeeId": 1,
                "payPeriod": {
                    "start_date": "2020-01-16",
                    "end_date": "2020-01-31"
                },
                "amountPaid": "80.0"
            },
        ]
    }
}
```

**Comment by chrisalley** [comment]
The following works:

config/environment.rb
```ruby
# Globally set JSON key format to lower camelcase.
Jbuilder.key_format camelize: :lower
Jbuilder.deep_format_keys true
```

_foo.json.jbuilder
```ruby
json.(foo, :id, :foo_name)
json.bars foo.bars do |bar|
  json.(bar, :id, :bar_name)
end
```
