### ISSUE TITLE
Capturing output as JSON Object

### ISSUE THREAD

**Issue by ramanbuttar** [rails/jbuilder#450]
I have a use case where instead of rendering the output as JSON, I'd like to capture it as a hash object and forward it to another library to render as XML.

```
json_string = render_to_string 'orders/get_order_detail.json', locals: {
    name: 'GetOrderDetail',
    errors: [{error_code: 'InvalidLogin', error_message: 'Invalid Webservice Login'}],
    is_successful: false,
    order: nil,
    record_count: 0.0
}

json_object = JSON.parse(json_string)
render soap: json_object
```

The `soap` renderer requires a hash object, as opposed to a JSON string, which is what `jbuilder` produces. What's a better approach to this instead of having to render to string and then parse back to a hash? That's wasteful and time intensive.

**Comment by robin850** [comment]
Actually, this kind of API doesn't really fit with Jbuilder. This library tries to give you a nice DSL to write *templates* for outputting JSON, this is not a serializer for your records. Maybe, you should rather look at [ActiveModel::Serializers](https://github.com/rails-api/active_model_serializers/tree/0-10-stable).

On the other hand, you can implement the `to_builder` method of your record like:

~~~ruby
class Order < ApplicationRecord
  def to_builder
    Jbuilder.new do |order|
      order.extract! self, :id, :title
      # ...
    end
  end
end
~~~

And then you can have a Hash representation of your record with:

~~~ruby
# In your JSON template
json.merge! order.to_builder.attributes!

# In your SOAP controller
render soap: order.to_builder.attributes!
~~~

**But** you won't have access to features such as `partial!` and this is more painful to inject locals as you have in your example.
