### ISSUE TITLE
MultiJson to stdlib changed default timestamp serialization

### ISSUE THREAD

**Issue by oehlschl** [rails/jbuilder#462]
We noticed some new test failures in our Rails app after updating from jbuilder 2.8->2.9 and tracked them to when MultiJson was dropped in b952ae0 ; that is the first commit in which these tests fail.

It looks like the serializations of some datetime objects are different between the MultiJson and stdlib JSON:

```ruby
-  "createdAt"=>"2019-05-14T15:33:16.643Z", # before
+  "createdAt"=>"2019-05-14 15:33:16 UTC", # after
```

Is this something that can be shimmed for the sake of backwards compatibility?

Thanks!

**Comment by georgeclaghorn** [comment]
We’re covering this in #461. Thanks for the report!
