### ISSUE TITLE
Output simple field values from blocks

### ISSUE THREAD

**Issue by toncid** [rails/jbuilder#464]
Is it possible to set a simple field value that is result of a `do-end` block:

```
json.some_field do
  if some_condition?
    42
  else
    13
  end
end
```

This would result with `some_field` as either 42 or 13 (`{"someField": 42}`), but in reality it is fully omitted from the output JSON.

**Comment by Richard-Degenne** [comment]
```ruby
json.some_field begin
  if some_condition?
    42
  else
    13
  end
end
```

Instead of giving your block to Jbuilder, evaluate it, and give Jbuilder the result.

**Comment by toncid** [comment]
Thanks!
