### ISSUE TITLE
Rails6 removed namespaced_file_path

### ISSUE THREAD

**Issue by kdiogenes** [rails/jbuilder#470]
This PR removed namespaced_file_path from Rails6: https://github.com/rails/rails/pull/27353

The jubilder controller template still uses this method: https://github.com/rails/jbuilder/blob/master/lib/generators/rails/templates/controller.rb#L2

I replaced this method by `namespaced_path` and all tests keep green.

Is there anything against this change?

**Comment by kdiogenes** [comment]
I also created a PR #471

**Comment by olleolleolle** [comment]
This is fixed in #471 - thank you for taking the time to describe and repair this!
