### ISSUE TITLE
New release for Ruby 2.7

### ISSUE THREAD

**Issue by connorshea** [rails/jbuilder#472]
I saw a deprecation warning from jbuilder when trying my test suite on Ruby 2.7, and it looks like it was already fixed in jbuilder master. Could we get a new release with the fix? :)

```
jbuilder-2.9.1/lib/jbuilder.rb:188: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
```

**Comment by huobazi** [comment]
```bash
/Users/xx/.gem/ruby/2.7.0/gems/jbuilder-2.9.1/lib/jbuilder.rb:66: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
```

**Comment by alex-mohemian** [comment]
Yes please!

**Comment by alejandroperea** [comment]
Same problem. Any news about this?

**Comment by otherguy** [comment]
It's pretty annoying that I now have to pull in the git master branch in my Gemfile 🤔

**Comment by kaspth** [comment]
Done:

https://github.com/rails/jbuilder/commit/e0ac4a1f2fa3d22f9f3bb94194ed499ca91cf40e
https://rubygems.org/gems/jbuilder/versions/2.10.0

Looks like the lone test failure was related to a Rails thing: https://travis-ci.org/rails/jbuilder/jobs/648198217?utm_medium=notification&utm_source=github_status

**Comment by connorshea** [comment]
Thanks!

**Comment by alejandroperea** [comment]
Thanks a lot @kaspth !
