### ISSUE TITLE
Missing Template for mobile view

### ISSUE THREAD

**Issue by Narf-stack** [rails/jbuilder#487]
Hi all,

I have been trying to render my json.jbuilder file on a mobile device, but I get the error " Missing Template". Since my rendering works correctly for my view "html.erb" and not for my "mobile.erb", I tried to create another json.jbuilder file dedicated to my mobile.erb view. But nothing changed.
Is there a way to achieve this ? 

Sorry if that sounds like a silly question, but I genuilly did not find any info on this matter.

**Comment by KapilSachdev** [comment]
This question is for stackoverflow as it doesn;t seems like an issue with the gem, but rather with your project.

As you haven't given much information about your project setup and file locations (which looks like a plausible issue there), you may check few things to get started
- is jbuilder exists for your mobile action.
- is jbuilder file is in the correct location as per project setup in `app/views`
- maybe try giving location explicitly like `render template: 'home/mobile'` here mobile.json.jbuilder is defined under `app/views/home/mobile.json.jbuilder`.

**Comment by Narf-stack** [comment]
Hi,

Sorry I forgot to closed that issue. I forgot how I did it, but I did find a workaround for my trouble.
Thank you for your help though.

**Comment by Narf-stack** [comment]
.
