### ISSUE TITLE
BigDecimals are wrapped in quotation marks

### ISSUE THREAD

**Issue by erikdahlstrand** [rails/jbuilder#79]
```
"variants": [
    {
        "price": "3460.50",
        "id": 1,
        "position": 0
    }
]
```

Should be:

```
"variants": [
    {
        "price": 3460.50,
        "id": 1,
        "position": 0
    }
]
```

**Comment by uberllama** [comment]
Blast from the past, as I just ran into this again. Looks like it was fixed in a fork but never merged into master? You should definitely not have to explicitly cast a decimal to a float.

**Comment by sdepold** [comment]
The respective pull request was rejected.

**Comment by besi** [comment]
The pull request is #80

**Comment by rwz** [comment]
JSON spec does not introduce any limits for floats or integers, but JavaScript engines that are used to parse this do. For instance JavaScript floats are represented with 64 bits, and integers only have 32 iirc.

So, Ruby's Bignum can theoretically be properly encoded into JSON, but none of the existing JavaScript engines would be able to parse it correctly. And Ruby's JSON and ActiveSupport tend to make it JavaScript compatible in the first place.

If you're absolutely sure your BigNums aren't gonna overflow, cast them to integers or floats before passing to Jbuilder.
